### ISSUE TITLE
ZeroDivisionError: float division by zero (fb-check-ttf.py line 2355)

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1043]
```
felipe@guarana:~/devel/github_felipesanches/fontbakery (master)*$ ./fontbakery-check-ttf.py ~/devel/github_google/fonts/apache/robotoslab/*.ttf --ghm --verbose
```
[...]
```
This font has already been processed with ttfautohint.
Traceback (most recent call last):
  File "./fontbakery-check-ttf.py", line 3706, in <module>
    main()
  File "./fontbakery-check-ttf.py", line 2355, in main
    change = float(hinted_size)/dehinted_size - 1
ZeroDivisionError: float division by zero
```

**Comment by felipesanches** [comment]
Detected while working on #1035 by running test_all_fonts.sh and looking at check_results/issues.txt

**Comment by felipesanches** [comment]
Division by zero is caused by dehinted_size = statinfo.st_size being zero which is the result of ttfautohint refusing to generate a new file, so the temp file we created remains empty:

```
felipe@guarana:~/devel/github_felipesanches/fontbakery (master)*$ ttfautohint --dehint /home/felipe/devel/github_google/fonts/apache/robotoslab/RobotoSlab-Bold.ttf /tmp/out.ttf
This font has already been processed with ttfautohint.
```

I'm not sure what ttfautohint means when it bails out the --dehint invokation with the message "This font has already been processed with ttfautohint."

**Comment by felipesanches** [comment]
I've logged the ttfautohing as a check-skip message (with a reference to this specific issue URL just in case) and this avoids the divide-by-zero crash gracefully.
