### ISSUE TITLE
UnboundLocalError: local variable 'n1' referenced before assignment

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1046]
```
Traceback (most recent call last):
  File "./fontbakery-check-ttf.py", line 3712, in <module>
    main()
  File "./fontbakery-check-ttf.py", line 2864, in main
    if len(n1) == 0 or len(n2) == 0 or n1[0] != n2[0]:
UnboundLocalError: local variable 'n1' referenced before assignment
```

**Comment by felipesanches** [comment]
Detected while working on #1035 and running this:

```
felipe@guarana:~/devel/github_felipesanches/fontbakery (master)*$ ./fontbakery-check-ttf.py ~/devel/github_google/fonts/ofl/baloopaaji/*.ttf --ghm --verbose
```
