### ISSUE TITLE
crash: Droid Serif Bold Italic

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1321]
```
ERROR    Font macStyle Italic bit is set but nameID 1 ("Droid Serif") is not ended with "Italic"  
ERROR    Canonical name in font: Expected "Droid Serif Bold" or "Droid Serif BoldItalic" but got "Droid Serif Bold Italic" instead.  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fontbakery-0.1.0-py2.7.egg/EGG-INFO/scripts/fontbakery-check-ttf.py", line 476, in <module>
    'error': args.error
  File "/usr/local/lib/python2.7/dist-packages/fontbakery-0.1.0-py2.7.egg/EGG-INFO/scripts/fontbakery-check-ttf.py", line 385, in fontbakery_check_ttf
    remote_style = remote.fullpath[:-4].split('-')[1]
IndexError: list index out of range
```

**Comment by felipesanches** [comment]
@m4rc1e This one crashes because it tries to split '-' on 'DroidSans.ttf' (expecting to extract a style from a filename with a 'DroidSans-Regular.ttf' naming scheme)...
