### ISSUE TITLE
Metadata.pb: don't try to open nonexistent fonts

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1372]
If I have a directory `/tmp/tmpqXJOLn/`, with the files

```
METADATA.pb
RobotoSlab-Thin.ttf
```

(The contents of `METADATA.pb` are at the bottom of this report.)

But `METADATA.pb` references more files than there are in the directory, I get an error and early exit like this (`stderr`):

```
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-check-ttf.py", line 531, in <module>
    'coverage': args.coverage
  File "/usr/local/bin/fontbakery-check-ttf.py", line 142, in fontbakery_check_ttf
    f.filename))
  File "/usr/local/bin/fontbakery-check-ttf.py", line 36, in ttf_cache
    cached_font_objects[key] = ttLib.TTFont(key)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 166, in __init__
    file = open(file, "rb")
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/py23.py", line 249, in open
    file, mode, buffering, encoding, errors, newline, closefd)
IOError: [Errno 2] No such file or directory: '/tmp/tmpqXJOLn/RobotoSlab-Light.ttf'
```

*NOTE* Fontbakery fails to open `RobotoSlab-Light.ttf` but there's only  `RobotoSlab-Thin.ttf`in the directory.

---
## METADATA.pb
```
name: "Roboto Slab"
designer: "Christian Robertson"
license: "APACHE2"
category: "SERIF"
date_added: "2013-04-10"
fonts {
  name: "Roboto Slab"
  style: "normal"
  weight: 100
  filename: "RobotoSlab-Thin.ttf"
  post_script_name: "RobotoSlab-Thin"
  full_name: "Roboto Slab Thin"
  copyright: "Copyright 2013 Google Inc. All Rights Reserved."
}
fonts {
  name: "Roboto Slab"
  style: "normal"
  weight: 300
  filename: "RobotoSlab-Light.ttf"
  post_script_name: "RobotoSlab-Light"
  full_name: "Roboto Slab Light"
  copyright: "Copyright 2013 Google Inc. All Rights Reserved."
}
fonts {
  name: "Roboto Slab"
  style: "normal"
  weight: 400
  filename: "RobotoSlab-Regular.ttf"
  post_script_name: "RobotoSlab-Regular"
  full_name: "Roboto Slab"
  copyright: "Copyright 2013 Google Inc. All Rights Reserved."
}
fonts {
  name: "Roboto Slab"
  style: "normal"
  weight: 700
  filename: "RobotoSlab-Bold.ttf"
  post_script_name: "RobotoSlab-Bold"
  full_name: "Roboto Slab Bold"
  copyright: "Copyright 2013 Google Inc. All Rights Reserved."
}

subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "greek"
subsets: "greek-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"

```

**Comment by felipesanches** [comment]
oh! I see! Makes sense. I can fix it :-)

**Comment by davelab6** [comment]
It shouldn't crash, but it should be making VERY LOUD COMPLAINTS. 

If I check in a METADATA file and forget to check in a font file that it references, I want FB to tell me very clearly I am doing something extremely unusual and probably very bad.

**Comment by felipesanches** [comment]
My commit includes warning messages about that.

Maybe a good way to stress (more loudly) the message could be by creating a new check that errors if any of the METADATA.pb-referenced TTFs are missing.

**Comment by davelab6** [comment]
Yes please:)
