### ISSUE TITLE
check-ttf.py: check_METADATA_Ensure_all_TTF_references_are_valid implementation error

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1381]
Seems an error was introduced in the check added to 1378e2f48a26271ff938666f90780529aae725a1

traceback on all families:
```
Traceback (most recent call last):
  File "bin/fontbakery-check-ttf.py", line 538, in <module>
    'coverage': args.coverage
  File "bin/fontbakery-check-ttf.py", line 333, in fontbakery_check_ttf
    checks.check_METADATA_Ensure_all_TTF_references_are_valid(fb, family)
AttributeError: 'module' object has no attribute 'check_METADATA_Ensure_all_TTF_references_are_valid'
```

**Comment by felipesanches** [comment]
Hmmm... Try re-installing FontBakery with:

```
python setup.py install
```

That should fix the problem for you, I think.

**Comment by m4rc1e** [comment]
Thanks, my bad. Closing
