### ISSUE TITLE
ImportError: No module named reporters.terminal

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1389]
@graphicore,

After **sudo python setup.py install** on the **refactor-architecture** branch, I get this ImportError when trying to invoke fb-check-gfonts:

```
felipe@guarana:~/fb-dev (refactor-architecture)*$ fontbakery-check-googlefonts.py -h
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-check-googlefonts.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.1.0', 'fontbakery-check-googlefonts.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/fontbakery-0.1.0-py2.7.egg/EGG-INFO/scripts/fontbakery-check-googlefonts.py", line 14, in <module>
    from fontbakery.reporters.terminal import TerminalReporter
ImportError: No module named reporters.terminal
```

This is possibly an issue with our current setup.py

**Comment by graphicore** [comment]
Hmm, I don't know what it is, but this is how I set it up:

```
$ virturalenv venv
$ . venv/bin/activate
$ pip install -e .
# bonus
$ . bin/bash_completion
```

**Comment by felipesanches** [comment]
OK. I just did that and now it is missing fonttools...

```
(venv) felipe@guarana:~/fb-dev (refactor-architecture)*$ fontbakery-check-googlefonts.py 
Traceback (most recent call last):
  File "/home/felipe/devel/github_felipesanches/fontbakery/venv/bin/fontbakery-check-googlefonts.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/felipe/devel/github_felipesanches/fontbakery/bin/fontbakery-check-googlefonts.py", line 16, in <module>
    from fontbakery.specifications.googlefonts import specificiation as specificiation
  File "/home/felipe/devel/github_felipesanches/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 22, in <module>
    from fontTools.ttLib import TTFont
ImportError: No module named fontTools.ttLib
(venv) felipe@guarana:~/fb-dev (refactor-architecture)*$ 
```

**Comment by graphicore** [comment]
maybe, in your virtualenv, you also need to do:

```
(venv)$ pip install -r requirements.txt
```

**Comment by graphicore** [comment]
(I would try this next) and I remember i complained somewhere ... #1367

**Comment by felipesanches** [comment]
Wunderbar !

It works :-) Thanks
