### ISSUE TITLE
OS X command line install error in Homebrew webfonttools cask

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#1409]
Attempted to install Font Bakery from the command line on OS X 10.12.5 using previously installed Homebrew and the instructions included on the README.

```▶ brew --version
Homebrew 1.2.3
Homebrew/homebrew-core (git revision b996; last commit 2017-06-28)
```

At the first step of the ots install that includes the tap of the webfonttools cask, I received the following error:

```
▶ brew tap davelab6/webfonttools
==> Tapping davelab6/webfonttools
Cloning into '/usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools'...
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/fonttools.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/fonttools.rb:6:in `<class:Fonttools>'
Please report this to the davelab6/webfonttools tap!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/ots.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/ots.rb:6:in `<class:Ots>'
Please report this to the davelab6/webfonttools tap!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/sfnt2woff-zopfli.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'
Please report this to the davelab6/webfonttools tap!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/sfnt2woff.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'
Please report this to the davelab6/webfonttools tap!
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/ttf2eot.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/davelab6/homebrew-webfonttools/ttf2eot.rb:6:in `<class:Ttf2eot>'
Please report this to the davelab6/webfonttools tap!
Error: Cannot tap davelab6/webfonttools: invalid syntax in tap!
```

It sounds like `Formula.sha1` is deprecated and the ruby scripts need to be updated to `Formula.sha256` in:

- `davelab6/homebrew-webfonttools/fonttools.rb:6:in <class:Fonttools>`
- `davelab6/homebrew-webfonttools/ots.rb:6:in <class:Ots>`
- `davelab6/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in <class:Sfnt2woffZopfli>`
- `davelab6/homebrew-webfonttools/sfnt2woff.rb:6:in <class:Sfnt2woff>`
- `davelab6/homebrew-webfonttools/ttf2eot.rb:6:in <class:Ttf2eot>`

**Comment by davelab6** [comment]
@chrissimpkins sorry my delay on this; I guess I said to tap me because I was ahead of Bram, but now his https://github.com/bramstein/homebrew-webfonttools is ahead of me, so use that and all should be well :)

**Comment by chrissimpkins** [comment]
@davelab6 no worries Dave!  Will give it a try.  This was based upon instructions on the README and it appears that it is updated now.  Appreciate your help.
