### ISSUE TITLE
com.google.fonts/test/004: UnicodeDecodeError

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1633]
When PRing https://github.com/google/fonts/pull/1287, I got the following error.

```
>> �[1;36;40mcom.google.fonts/test/004�[0m
   �[1;35;40mIs this a propper HTML snippet ?�[0m
 * �[1;37;41mERROR�[0m: Failed with UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 11: ordinal not in range(128)
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/testrunner.py", line 305, in _exec_test_generator
             for sub_result in gen:
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 191, in com_google_fonts_test_004
             if "<p>" not in data or "</p>" not in data:
         UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 11: ordinal not in range(128)
         

   Result: �[1;37;41mERROR�[0m
```

Also happened in https://github.com/google/fonts/pull/1281#issuecomment-339994524

**Comment by felipesanches** [comment]
thanks, Marc. I'll take care of this tomorrow.
