### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by pathumego** [googlefonts/fontbakery#1674]
Trying to install with `pip` on macOS and getting this.

```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/50/9325qhvn4z12wc0myvg7z9ch0000gn/T/pip-IRllRT-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by felipesanches** [comment]
You may want to install it on a python virtual environment (think of it as a safe and clean "sandbox" where things will install nicely regardless of any other things you may already have installed on your computer).

To do so, you can run these commands:

```
pip install virtualenv
virtualenv venv
. venv/bin/activate
pip install fontbakery
```

To use fontbakery you'll have to always activate the virtual environment by running ``. venv/bin/activate`` after opening the text terminal.

Then usage instructions are provided by ``fontbakery -h`` or on the README file here:
 
https://github.com/googlefonts/fontbakery/blob/master/README.md#install

**Comment by felipesanches** [comment]
After the basic install, you may want to also install third-party complementary tools, by following the resto of the install instructions available at:

https://github.com/googlefonts/fontbakery/blob/master/README.md#install

**Comment by felipesanches** [comment]
@pathumego Let me know if this works well for you. Thanks for the MacOS feedback! It is always useful to hear from the users :-)

**Comment by madig** [comment]
I usually use `pip install --user ...`. Fontbakery installed fine for me with that.

**Comment by pathumego** [comment]
@felipesanches Thanks! It worked without any hiccups on virtual environment. I will post if there are any issues while using it :)
