### ISSUE TITLE
Only run variable font tests on variable fonts

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1723]
Hey,

Variable tests 167-172 are being run on every font.

```
>> com.google.fonts/check/167 with ((u'font[0]', '/Users/marc/Downloads/Google_Korean-3/fix/Poorstory-Regular.ttf'),)
   The variable font 'wght' (Weight) axis coordinate must be 400 on the 'Regular' instance.
 * ERROR: The condition <FontBakeryCondition:regular_wght_coord> had an error: KeyError: 'fvar'
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 383, in _evaluate_condition
             return None, condition(**args)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/callable.py", line 78, in __call__
             return self._func(*args, **kwds)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5193, in regular_wght_coord
             return get_instance_axis_value(ttFont, "Regular", "wght")
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5178, in get_instance_axis_value
             for i in ttFont["fvar"].instances:
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 415, in __getitem__
             data = self.reader[tag]
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/sfnt.py", line 113, in __getitem__
             entry = self.tables[Tag(tag)]
         KeyError: 'fvar'


   Result: ERROR

>> com.google.fonts/check/168 with ((u'font[0]', '/Users/marc/Downloads/Google_Korean-3/fix/Poorstory-Regular.ttf'),)
   The variable font 'wdth' (Width) axis coordinate must be 100 on the 'Regular' instance.
 * ERROR: The condition <FontBakeryCondition:regular_wdth_coord> had an error: KeyError: 'fvar'
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 383, in _evaluate_condition
             return None, condition(**args)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/callable.py", line 78, in __call__
             return self._func(*args, **kwds)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5205, in regular_wdth_coord
             return get_instance_axis_value(ttFont, "Regular", "wdth")
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5178, in get_instance_axis_value
             for i in ttFont["fvar"].instances:
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 415, in __getitem__
             data = self.reader[tag]
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/sfnt.py", line 113, in __getitem__
             entry = self.tables[Tag(tag)]
         KeyError: 'fvar'


   Result: ERROR

>> com.google.fonts/check/169 with ((u'font[0]', '/Users/marc/Downloads/Google_Korean-3/fix/Poorstory-Regular.ttf'),)
   The variable font 'slnt' (Slant) axis coordinate must be zero on the 'Regular' instance.
 * ERROR: The condition <FontBakeryCondition:regular_slnt_coord> had an error: KeyError: 'fvar'
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 383, in _evaluate_condition
             return None, condition(**args)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/callable.py", line 78, in __call__
             return self._func(*args, **kwds)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5211, in regular_slnt_coord
             return get_instance_axis_value(ttFont, "Regular", "slnt")
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5178, in get_instance_axis_value
             for i in ttFont["fvar"].instances:
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 415, in __getitem__
             data = self.reader[tag]
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/sfnt.py", line 113, in __getitem__
             entry = self.tables[Tag(tag)]
         KeyError: 'fvar'


   Result: ERROR

>> com.google.fonts/check/170 with ((u'font[0]', '/Users/marc/Downloads/Google_Korean-3/fix/Poorstory-Regular.ttf'),)
   The variable font 'ital' (Italic) axis coordinate must be zero on the 'Regular' instance.
 * ERROR: The condition <FontBakeryCondition:regular_ital_coord> had an error: KeyError: 'fvar'
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 383, in _evaluate_condition
             return None, condition(**args)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/callable.py", line 78, in __call__
             return self._func(*args, **kwds)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5217, in regular_ital_coord
             return get_instance_axis_value(ttFont, "Regular", "ital")
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5178, in get_instance_axis_value
             for i in ttFont["fvar"].instances:
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 415, in __getitem__
             data = self.reader[tag]
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/sfnt.py", line 113, in __getitem__
             entry = self.tables[Tag(tag)]
         KeyError: 'fvar'


   Result: ERROR

>> com.google.fonts/check/171 with ((u'font[0]', '/Users/marc/Downloads/Google_Korean-3/fix/Poorstory-Regular.ttf'),)
   The variable font 'opsz' (Optical Size) axis coordinate should be between 9 and 13 on the 'Regular' instance.
 * ERROR: The condition <FontBakeryCondition:regular_opsz_coord> had an error: KeyError: 'fvar'
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 383, in _evaluate_condition
             return None, condition(**args)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/callable.py", line 78, in __call__
             return self._func(*args, **kwds)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5223, in regular_opsz_coord
             return get_instance_axis_value(ttFont, "Regular", "opsz")
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5178, in get_instance_axis_value
             for i in ttFont["fvar"].instances:
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 415, in __getitem__
             data = self.reader[tag]
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/sfnt.py", line 113, in __getitem__
             entry = self.tables[Tag(tag)]
         KeyError: 'fvar'


   Result: ERROR

>> com.google.fonts/check/172 with ((u'font[0]', '/Users/marc/Downloads/Google_Korean-3/fix/Poorstory-Regular.ttf'),)
   The variable font 'wght' (Weight) axis coordinate must be 700 on the 'Bold' instance.
 * ERROR: The condition <FontBakeryCondition:bold_wght_coord> had an error: KeyError: 'fvar'
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 383, in _evaluate_condition
             return None, condition(**args)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/callable.py", line 78, in __call__
             return self._func(*args, **kwds)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5199, in bold_wght_coord
             return get_instance_axis_value(ttFont, "Bold", "wght")
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5178, in get_instance_axis_value
             for i in ttFont["fvar"].instances:
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/__init__.py", line 415, in __getitem__
             data = self.reader[tag]
           File "/Users/marc/Documents/googlefonts/fontbakery/env/lib/python2.7/site-packages/fontTools/ttLib/sfnt.py", line 113, in __getitem__
             entry = self.tables[Tag(tag)]
         KeyError: 'fvar'

   Result: ERROR
```

Try it on any non variable font

**Comment by felipesanches** [comment]
This seemed weird at first because all of these checks do have `is_variable_font` listed as a condition and the condition is clearly false when an fvar table is lacking.

But then I noticed that the problem was on the second condition of each of these checks. All of them are derived from `get_instance_axis_value`. And that was crashing when computing the condition. So I solved this by adding a safety check right in the beginning of `get_instance_axis_value` to return `None` if `is_variable_font(ttFont)` is False.
