### ISSUE TITLE
Progress bar crashes scripts in Windows Powershell

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1735]
## Observed behaviour

Running fontbakery-check-googlefonts.py on Windows throws this backtrace:
```
Traceback (most recent call last):
  File "C:\UsersLocal\nikolaus.waxweiler\Development\tmp\fontbakery-venv/Scripts\fontbakery-check-specification.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "C:\UsersLocal\nikolaus.waxweiler\Development\fontbakery\bin\fontbakery-check-specification.py", line 7, in <module>
    main()
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\commands\check_spec.py", line 206, in main
    distribute_generator(runner.run(), reporters)
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\checkrunner.py", line 689, in distribute_generator
    target(item)
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\reporters\__init__.py", line 109, in receive
    self._output(event)
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\reporters\terminal.py", line 214, in _output
    text = self._render_event(*event)
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\reporters\terminal.py", line 517, in _render_event
    self._render_event_async(print, event)
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\reporters\terminal.py", line 509, in _render_event_async
    self._render_event_sync(print, event)
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\reporters\terminal.py", line 405, in _render_event_sync
    self.stdout.write(text)
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\reporters\terminal.py", line 160, in write
    self.flush();
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\reporters\terminal.py", line 166, in flush
    progressbar, reset_progressbar = self._draw_progressbar();
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\reporters\terminal.py", line 313, in draw_progressbar
    rows, columns = map(int, os.popen('stty size', 'r').read().split())
ValueError: need more than 0 values to unpack
```

## Expected behaviour

Progress bar should display or be disabled. Using `-n` works.

## Resources and exact process needed to replicate

Use fontbakery scripts in a Powershell (Powershell 6.x works on Linux, Windows and macOS: https://github.com/PowerShell/PowerShell).

**Comment by felipesanches** [comment]
thanks for reporting this!

**Comment by felipesanches** [comment]
does it still crash or was this already addressed somehow?

**Comment by madig** [comment]
I think we fixed this by disabling the progress bar on Windows by default.
