### ISSUE TITLE
ERROR: com.google.fonts/check/037 with CabinVFBeta-Italic.ttf

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1765]
with the file `fontbakery/data/test/cabinvfbeta/CabinVFBeta-Italic.ttf`

```
>> com.google.fonts/check/037 with ((u'font[0]', './data/test/cabinvfbeta/CabinVFBeta-Italic.ttf'),)
   Checking with Microsoft Font Validator.
 * ERROR: Failed with OSError: [Errno 2] No such file or directory: './data/test/cabinvfbeta/fval.xsl'
         Traceback (most recent call last):
           File "/home/commander/Projekte/fontdev/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 329, in _exec_check_generator
             for sub_result in gen:
           File "/home/commander/Projekte/fontdev/googlefonts/fontbakery/Lib/fontbakery/specifications/general.py", line 139, in com_google_fonts_check_037
             os.remove(fval_file)
         OSError: [Errno 2] No such file or directory: './data/test/cabinvfbeta/fval.xsl'
         

   Result: ERROR
```

**Comment by felipesanches** [comment]
This does not ERROR anymore nowadays.
