### ISSUE TITLE
[reporters][markdown] traceback when checking AmaticSC

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1870]
Attempted to gen a markdown report for [AmaticSC-Regular](https://github.com/googlefonts/AmaticSC/tree/master/fonts/ttf) and got the following traceback.

```
Traceback (most recent call last):
  File "/Users/marc/Documents/googlefonts/fontbakery/venv/bin/fontbakery", line 9, in <module>
    load_entry_point('fontbakery==0.3.5.dev231+g127ce2e4', 'console_scripts', 'fontbakery')()
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/cli.py", line 24, in main
    "fontbakery.commands." + subcommand_module, run_name='__main__')
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/commands/check_googlefonts.py", line 31, in <module>
    sys.exit(main())
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/commands/check_specification.py", line 285, in main
    args.ghmarkdown.write(mdr.get_markdown())
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/reporters/ghmarkdown.py", line 79, in get_markdown
    if self.omit_loglevel(check["result"]):
TypeError: list indices must be integers, not unicode

```

CLI I used was:

```
fontbakery check-googlefonts -l FAIL ./AmaticSC/fonts/ttf/AmaticSC-Regular.ttf -g *check --ghmarkdown plus.md

```

**Comment by felipesanches** [comment]
## Fontbakery report

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> METADATA.pb: Ensure designer simple short name.</summary>

* [com.google.fonts/check/080](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/080)
* **FAIL** [:fire:] "designer" key must be simple short name

</details>
<br>
</details>
<details>
<summary><b>[3] AmaticSC-Regular.ttf</b></summary>
<details>
<summary>:broken_heart: <b>ERROR:</b> Checking with ftxvalidator.</summary>

* [com.google.fonts/check/035](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/035)
* **ERROR** [:broken_heart:] ftxvalidator is not available!

</details>
<details>
<summary>:broken_heart: <b>ERROR:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* **ERROR** [:broken_heart:] Mono runtime and/or Microsoft Font Validator are not available!
* **ERROR** [:broken_heart:] Failed with OSError: [Errno 2] No such file or directory

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking font version fields (head and name table).</summary>

* [com.google.fonts/check/044](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/044)
* **FAIL** [:fire:] head version is ('2', u'50499'), name version string for platform 1, encoding 0, is ('2', u'505') [code: mismatch]
* **FAIL** [:fire:] head version is ('2', u'50499'), name version string for platform 3, encoding 1, is ('2', u'505') [code: mismatch]

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :doughnut: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 2 | 2 | 5 | 15 | 5 | 103 |
| 0% | 0% | 0% | 1% | 0% | 5% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**

**Comment by felipesanches** [comment]
OK, I think I fixed it by also taking care ofcheck clusters. I'll push the fix that generated the report from my last message above.

**Comment by felipesanches** [comment]
Oh! It was a simple, silly mistake. Now percentage computation is fixed as well  :-D :tada: 

## Fontbakery report

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> METADATA.pb: Ensure designer simple short name.</summary>

* [com.google.fonts/check/080](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/080)
* **FAIL** [:fire:] "designer" key must be simple short name

</details>
<br>
</details>
<details>
<summary><b>[3] AmaticSC-Regular.ttf</b></summary>
<details>
<summary>:broken_heart: <b>ERROR:</b> Checking with ftxvalidator.</summary>

* [com.google.fonts/check/035](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/035)
* **ERROR** [:broken_heart:] ftxvalidator is not available!

</details>
<details>
<summary>:broken_heart: <b>ERROR:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* **ERROR** [:broken_heart:] Mono runtime and/or Microsoft Font Validator are not available!
* **ERROR** [:broken_heart:] Failed with OSError: [Errno 2] No such file or directory

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking font version fields (head and name table).</summary>

* [com.google.fonts/check/044](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/044)
* **FAIL** [:fire:] head version is ('2', u'50499'), name version string for platform 1, encoding 0, is ('2', u'505') [code: mismatch]
* **FAIL** [:fire:] head version is ('2', u'50499'), name version string for platform 3, encoding 1, is ('2', u'505') [code: mismatch]

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 2 | 2 | 5 | 15 | 5 | 103 |
| 2% | 2% | 4% | 11% | 4% | 78% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**

**Comment by m4rc1e** [comment]
Thank you for implementing this so quickly.

**Comment by felipesanches** [comment]
:fire: :warning: :fire_engine: :fire_engine: :fire_engine: ...

**Comment by felipesanches** [comment]
By the way... Do we care about all those FontVal **FAIL**s ?

**Comment by m4rc1e** [comment]
These one are legit.

We can ignore overlapping contours and points not on extremes though.
