### ISSUE TITLE
Need more detailed stack trace when test blows up

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1905]
## Observed behaviour

```
>> com.daltonmaag/check/something with (('font[0]', '[...]'),)
   Something
 * ERROR: Failed with IndexError: list index out of range
           File "C:\Users\nikolaus.waxweiler\AppData\Local\pypoetry\Cache\virtualenvs\damacheck-py3.6\lib\site-packages\fontbakery\checkrunner.py", line 347, in _exec_check_generator
             for sub_result in gen:


   Result: ERROR
```

## Expected behaviour

Should show me error line from within test.

**Comment by graphicore** [comment]
I'm not sure if we can get more information at this point. Also, it's hard to reproduce this way. Is the reporting/stack trace be better if you run the generator outside of checkrunner (e.g. call it by hand)?

**Comment by madig** [comment]
```
>>> list(check(ufo))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\UsersLocal\nikolaus.waxweiler\Development\damacheck\damacheck\dama_ufo.py", line 214, in something
    on_curve_point = contour[next_point_index]
  File "C:\Users\nikolaus.waxweiler\AppData\Local\pypoetry\Cache\virtualenvs\damacheck-py3.6\lib\site-packages\defcon\objects\contour.py", line 237,
in __getitem__
    return self._points.__getitem__(index)
IndexError: list index out of range
```
This tells me more.

**Comment by graphicore** [comment]
https://github.com/googlefonts/fontbakery/blob/d825e128447dbaecf640a96a46a851b3a3c748a8/Lib/fontbakery/checkrunner.py#L346-L357

Looks straight forward to me. Do you have any ideas how to improve it?

How's your Traceback when you do:

```py
gen = check(ufo);
for sub_result in gen: pass
```

I wonder if this is some kind of python limitation or if the `get_traceback` method is not good enough.

**Comment by graphicore** [comment]
Is the reporting better in python 2? I just found this: https://stackoverflow.com/a/11415140/1315369 maybe we need to distinguish between python versions.

**Comment by madig** [comment]
Now that we're 3.6+ only, we can use Exception.__traceback__ unconditionally 😃 Having a look at the code...

**Comment by madig** [comment]
Still to do: see what can be done to get better tracebacks when conditions explode.
