### ISSUE TITLE
Python errors after fresh install

### ISSUE THREAD

**Issue by djrrb** [googlefonts/fontbakery#1993]
This might be due to a bad install, but I was told it was okay to report error messages that I get. So far all of the tests I have run have resulted in a python error, leading me to believe it is me and not you. But thanks so much for any ideas you may have about this!

## Observed behaviour

After a fresh install in a virtual environment, I am getting the following error.

```
(fb) DJR:Roslindale_TTF $ cd /Users/david/Desktop/workspace/FB/fb-Amstelvar/fonts
(fb) DJR:fonts $ fontbakery check-googlefonts *.ttf
Traceback (most recent call last):
  File "/Users/david/fb/bin/fontbakery", line 11, in <module>
    sys.exit(main())
  File "/Users/david/fb/lib/python3.5/site-packages/fontbakery/cli.py", line 22, in main
    "fontbakery.commands." + subcommand_module, run_name='__main__')
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 185, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/david/fb/lib/python3.5/site-packages/fontbakery/commands/check_googlefonts.py", line 5, in <module>
    from fontbakery.specifications.googlefonts import specification
  File "/Users/david/fb/lib/python3.5/site-packages/fontbakery/specifications/googlefonts.py", line 274
    yield PASS, f"{font} is named canonically."
                                              ^
SyntaxError: invalid syntax
```

Similarly, if I try to run `check-opentype` I get this error:

```
(fb) DJR:fonts $ fontbakery check-opentype *.ttf
Traceback (most recent call last):
  File "/Users/david/fb/bin/fontbakery", line 11, in <module>
    sys.exit(main())
  File "/Users/david/fb/lib/python3.5/site-packages/fontbakery/cli.py", line 22, in main
    "fontbakery.commands." + subcommand_module, run_name='__main__')
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 185, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/david/fb/lib/python3.5/site-packages/fontbakery/commands/check_opentype.py", line 5, in <module>
    import fontbakery.specifications.opentype
  File "/Users/david/fb/lib/python3.5/site-packages/fontbakery/specifications/opentype.py", line 1, in <module>
    from fontbakery.fonts_spec import spec_factory  # NOQA pylint: disable=unused-import
  File "/Users/david/fb/lib/python3.5/site-packages/fontbakery/fonts_spec.py", line 6, in <module>
    from fontbakery.checkrunner import Spec
  File "/Users/david/fb/lib/python3.5/site-packages/fontbakery/checkrunner.py", line 61
    return f'<Status {self.__name}>'
                                   ^
SyntaxError: invalid syntax
```

## Expected behaviour

I would like to see the results of the tests in my terminal window.

## Resources and exact process needed to replicate

Running from a local clone of this folder: https://github.com/TypeNetwork/Amstelvar/tree/master/fonts

Thank you :-)

**Comment by anthrotype** [comment]
Are you using python 3.6 or greater?

**Comment by anthrotype** [comment]
It looks like you are trying to run fontbakery with python 3.5. You need at least 3.6

**Comment by djrrb** [comment]
😳 oops. Upgraded and it works just as expected. Thank you!

**Comment by graphicore** [comment]
We could detect the python interpreter version and exit with a useful message.
