### ISSUE TITLE
Test for font names in other font catalogs

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#228]
- [x] Write a test to take the `$familyname` in METADATA.json and check if `http://www.myfonts.com/search/$fontname/`returns a page containing the string `I’ve got nothing.`
- [x] This url should fail the test, http://www.myfonts.com/search/oxygen/
- [x] This url should pass the test, http://www.myfonts.com/search/xxxxxxxxxxxxx/

Then,

- [x] specify a test for daltonmaag.com
- [x] specify a test for fonts.com
- [x] specify a test for fontshop.com
- [x] specify a test for fontsmith.com
- [x] specify a test for fontbureau.com
- [x] specify a test for houseind.com
- [x] specify a test for terminaldesign.com
- [x] specify a test for typography.com
- [x] specify a test for veer.com
- [ ] test Lineto
- [x] test Optimo, 
- [x] test Swiss Typefaces, 
- [x] test Nouvelle Noire, 
- [x] test EuropaType, 
- [x] test TypeDifferent, 
- [x] test Grilli Type
- [x] test Bold Monday
- [x] test Commercial Type, 
- [ ] test OurType, 
- [x] test The Enschedé Font Foundry
- [x] test Letterror
- [ ] test all vendors in https://github.com/xen/fontbakery/blob/master/docs/blacklist.markdown
- [ ] test all vendors in http://listgeeks.com/#!/view/type-foundries-not-on-typekit-1/by/GoranSoderstrom

**Comment by davelab6** [comment]
@felipesanches This no longer works...

```
$ fontbakery-crawl.py 
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-crawl.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.0.13', 'fontbakery-crawl.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.13-py2.7.egg/EGG-INFO/scripts/fontbakery-crawl.py", line 32, in <module>
    from bakery.crawl.scrapes import familynames
ImportError: No module named bakery.crawl.scrapes
$
```

**Comment by davelab6** [comment]
@felipesanches aha, per https://github.com/googlefonts/fontbakery/issues/494 it was moved to another repo - https://github.com/googlefonts/namecheck
