### ISSUE TITLE
module 'importlib.util' has no attribute 'profile_from_file_location'

### ISSUE THREAD

**Issue by kontur** [googlefonts/fontbakery#2511]
## Observed behaviour

Attempting to run a custom profile via the `$ fontbakery check-profile …` command a module error is emitted.

## Expected behaviour

Run the specified profile.

## Resources and exact process needed to replicate

Installing either from a local repo via `$ pip install .` or via `$ pip install fontbakery` (v0.7.4) will have the same result.

The command I run is:
`$ fontbakery check-profile /path/to/profile.py /path/to/any/ttffile.ttf` with the `profile.py` containing "Commented line-by-line" [example from the docs](https://font-bakery.readthedocs.io/en/latest/developer/writing-profiles.html#running-profiles).

It appears to me [importlib](https://docs.python.org/3/library/importlib.html#module-importlib.util) has no such methods as called in [commands/check_profile.py on lines 176/177](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/commands/check_profile.py#L176).

## Traceback
```
Traceback (most recent call last):
  File "/Users/johannes/tmp/venv/bin/fontbakery", line 10, in <module>
    sys.exit(main())
  File "/Users/johannes/tmp/venv/lib/python3.7/site-packages/fontbakery/cli.py", line 22, in main
    "fontbakery.commands." + subcommand_module, run_name='__main__')
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/johannes/tmp/venv/lib/python3.7/site-packages/fontbakery/commands/check_profile.py", line 318, in <module>
    sys.exit(main())
  File "/Users/johannes/tmp/venv/lib/python3.7/site-packages/fontbakery/commands/check_profile.py", line 217, in main
    profile = get_profile()
  File "/Users/johannes/tmp/venv/lib/python3.7/site-packages/fontbakery/commands/check_profile.py", line 202, in get_profile
    imported = get_module(args.profile)
  File "/Users/johannes/tmp/venv/lib/python3.7/site-packages/fontbakery/commands/check_profile.py", line 186, in get_module
    imported = get_module_from_file(name)
  File "/Users/johannes/tmp/venv/lib/python3.7/site-packages/fontbakery/commands/check_profile.py", line 176, in get_module_from_file
    profile = importlib.util.profile_from_file_location(module_name, filename)
AttributeError: module 'importlib.util' has no attribute 'profile_from_file_location'
```

**Comment by anthrotype** [comment]
looks like a blind find-and-replace:
https://github.com/googlefonts/fontbakery/commit/782211cc87e88782b2c2873e8900f06bd4416c95

the method name is "spec_from_file_location"

**Comment by kontur** [comment]
Thanks @anthrotype 👋 

Seemed like an easy first PR 😊 ☝️

**Comment by felipesanches** [comment]
Thanks, @kontur :-)

**Comment by felipesanches** [comment]
Johannes, please consider joining our FontBakery gitter chat at: https://gitter.im/fontbakery/Lobby
