### ISSUE TITLE
fontbakery version check without network access

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#2579]
## Observed behaviour

```
com.google.fonts/check/fontbakery_version
   Do we have the latest version of FontBakery installed?
```

I ran fontbakery without network access and received the following error message:

```
>> com.google.fonts/check/fontbakery_version
   Do we have the latest version of FontBakery installed?
 * ERROR: Running 'pip search fontbakery' returned an error code. Output follows :

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10ef55150>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /pypi
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10ef55690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /pypi
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10ef55810>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /pypi
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10ef55a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /pypi
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10ef55890>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /pypi
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/search.py", line 48, in run
    pypi_hits = self.search(query, options)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/search.py", line 65, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/download.py", line 831, in request
    headers=headers, stream=True)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/download.py", line 439, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi (Caused by NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10ef55550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))



   Result: ERROR
```

## Expected behaviour

Catch ConnectionError and handle this with a more informative message that network was not detected and this version check could not be completed at maybe the info or warning level?

**Comment by felipesanches** [comment]
I agree. But it should be a FAIL-level result, because we need to ensure the latest fontbakery version is being used, otherwise all other checks would be implementing an outdated quality-assurance policy.

**Comment by chrissimpkins** [comment]
For this issue though, the graceful exit would be to ignore the check and allow the user to run their installed version of the tool despite the fact that it is not able to confirm that the current version is installed.  It is not clear that there is a FAIL against the current version check, only that the tool can't tell because it can't access current release data.

**Comment by felipesanches** [comment]
If it can't tell, then in my opinion it is a FAIL ;-)

(because it will necessarily have to be run again to figure out what's the actual status)

**Comment by felipesanches** [comment]
Otherwise we risk a full-PASS report based on checks that could perhaps be outdated.

**Comment by felipesanches** [comment]
well... in other words, it is mandatory to get a full-PASS report with the latest version of fontbakery before considering that a font is in an acceptably good state. A FAIL in this check would ensure that holds true.
