### ISSUE TITLE
adobefonts profile causing traceback

### ISSUE THREAD

**Issue by bobh0303** [googlefonts/fontbakery#2631]
## Observed behaviour

`fontbakery check-adobefonts` causes traceback during reporting, resulting in empty report file.

## Expected behaviour

No traceback occurs and report file is not empty.

## Resources and exact process needed to replicate

- Download [NotoMono-Regular.ttf](https://www.google.com/get/noto/#mono-mono) or use any handy ttf file.
- From command line run:
```
fontbakery check-adobefonts --html out.html NotoMono-Regular.ttf
```
- Tests seem to run to completion but results in traceback:
```
DONE!

Traceback (most recent call last):
  File "/usr/local/bin/fontbakery", line 11, in <module>
    load_entry_point('fontbakery', 'console_scripts', 'fontbakery')()
  File "/smith/fontbakery/Lib/fontbakery/cli.py", line 22, in main
    "fontbakery.commands." + subcommand_module, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/smith/fontbakery/Lib/fontbakery/commands/check_adobefonts.py", line 30, in <module>
    sys.exit(main())
  File "/smith/fontbakery/Lib/fontbakery/commands/check_profile.py", line 311, in main
    args.html.write(hr.get_html())
  File "/smith/fontbakery/Lib/fontbakery/reporters/html.py", line 65, in get_html
    self.html_for_check(result),
  File "/smith/fontbakery/Lib/fontbakery/reporters/html.py", line 106, in html_for_check
    check["logs"].sort(key=lambda c: LOGLEVELS.index(c["status"]))
  File "/smith/fontbakery/Lib/fontbakery/reporters/html.py", line 106, in <lambda>
    check["logs"].sort(key=lambda c: LOGLEVELS.index(c["status"]))
ValueError: 'DEBUG' is not in list
```
and the `out.html` file is zero length.

Same things happens with `--ghmarkdown` reporting.

However, if neither reporter is used, e.g., `fontbakery check-adobefonts  NotoMono-Regular.ttf` then no traceback occurs.

**Comment by bobh0303** [comment]
I'm running from source, commit 0b91e8f860a9fe9877b4ca81fd58c843ed57192e
