### ISSUE TITLE
Cannot use --loglevel option with check-profile subcommand

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#2711]
```
macOS 10.15.1
$ fontbakery --version
0.7.15
```
I am attempting to apply the log level filter with the check-profile subcommand using the following:

```
fontbakery check-profile --loglevel WARN profile/check-valid.py build/Valid/static/*.ttf
```

and I receive the following exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontbakery/cli.py", line 22, in main
    "fontbakery.commands." + subcommand_module, run_name='__main__')
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/fontbakery/commands/check_profile.py", line 318, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontbakery/commands/check_profile.py", line 217, in main
    profile = get_profile()
  File "/usr/local/lib/python3.7/site-packages/fontbakery/commands/check_profile.py", line 202, in get_profile
    imported = get_module(args.profile)
  File "/usr/local/lib/python3.7/site-packages/fontbakery/commands/check_profile.py", line 190, in get_module
    imported = import_module(name, package=None)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'WARN'
```

I can verify that the profile runs without issues when I eliminate the `--loglevel WARN` flag

**Comment by chrissimpkins** [comment]
Hmmm...works fine when you include a `=` between the option and argument:

```
$ fontbakery check-profile --loglevel=WARN profile/check-valid.py build/Valid/static/*.ttf
```

but with the universal profile you don't need the `=` and `--help` indicates that a space is OK.

**Comment by graphicore** [comment]
> but with the universal profile you don't need the = and --help indicates that a space is OK.

interesting, I'd expect the long version of an option to be `--{name}={value}` and the short version `-{n} {value}`. So, maybe accepting `--loglevel WARN` is the bug, but actually, `-l WARN`raises as well.

The actual problem is, that in `commands/check_profile.py` a dummy `ArgumentParser` is used to 

> Prefetch the profile module, to fill some holes in the help text.

That only knows one argument `argument_parser.add_argument('profile')`, and then is called like this: `args, _ = argument_parser.parse_known_args()`.

To enable parsing the existing options correctly, we should somehow make the dummy parser familiar with them. Maybe, it's even easier to use the actual parser twice, but make it accept a none-profile version in the first run.

This is the current relevant code: 

https://github.com/googlefonts/fontbakery/blob/2ed6abcc99622386be463bec7209642dd1939a02/Lib/fontbakery/commands/check_profile.py#L193-L206

A PR with my suggestion follows in a second. I suggests someone tests it before merge. :grinning:

**Comment by chrissimpkins** [comment]
Thanks Lasse!  I pulled your branch and confirmed that this fixes the issue.  I really appreciate it.
