### ISSUE TITLE
trying new install on osx big sur at pip3 install fontbakery

### ISSUE THREAD

**Issue by cdeliason** [googlefonts/fontbakery#3360]
following the Mac install directions, and after "pip3 install fontbakery" I get:
```
[various successful downloads]...
Collecting opentype-sanitizer>=7.1.9 (from fontbakery)
  Downloading https://files.pythonhosted.org/packages/7a/a8/f8058ecb3bce155789ac4b480ce7efdca7ae6915d303f1043cc24f0bbd9f/opentype-sanitizer-8.1.4.post2.tar.gz (141kB)
     |████████████████████████████████| 143kB 14.3MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-_zyrgtxi/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel setuptools_scm 'meson >= 0.48' ninja
       cwd: None
  Complete output (50 lines):
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/4e/78/56aa1b5f4d8ac548755ae767d84f0be54fdd9d404197a3d9e4659d272348/setuptools-57.0.0-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
  Collecting setuptools_scm
    Downloading https://files.pythonhosted.org/packages/c4/d5/e50358c82026f44cd8810c8165002746cd3f8b78865f6bcf5d7f0fe4f652/setuptools_scm-6.0.1-py3-none-any.whl
  Collecting meson>=0.48
    Downloading https://files.pythonhosted.org/packages/e6/e4/11fc433adb18567dcf90041c54e5e65b03e9451bc1a45f9cd2dac9e9bb05/meson-0.58.1.tar.gz (1.9MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting ninja
    Downloading https://files.pythonhosted.org/packages/55/a3/56376f09d6be4be5b7ebfc492d3e89cb05206a61f8c5f695a5d1e8cc49b7/ninja-1.10.0.post2.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Building wheels for collected packages: meson, ninja
    Building wheel for meson (PEP 517): started
    Building wheel for meson (PEP 517): finished with status 'done'
    Created wheel for meson: filename=meson-0.58.1-cp38-none-any.whl size=758341 sha256=5d25342676ef682e0dfb310c1d5a680988fb69b71989b3156cca68db648d4592
    Stored in directory: /Users/xadm-cdeliason/Library/Caches/pip/wheels/5d/b6/74/f4181f4e2320e75faf1b694790dcf3e84c3cb9ff8379a03d78
    Building wheel for ninja (PEP 517): started
    Building wheel for ninja (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpmgep5g8q
         cwd: /private/tmp/pip-install-79jn83tr/ninja
    Complete output (9 lines):
      File "/private/tmp/pip-build-env-pal3uvds/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 560, in setup
        cmkr = cmaker.CMaker(cmake_executable)
      File "/private/tmp/pip-build-env-pal3uvds/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 95, in __init__
        self.cmake_version = get_cmake_version(self.cmake_executable)
      File "/private/tmp/pip-build-env-pal3uvds/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 81, in get_cmake_version
        raise SKBuildError(
    Traceback (most recent call last):
  
    Problem with the CMake installation, aborting build. CMake executable is cmake
    ----------------------------------------
    ERROR: Failed building wheel for ninja
    Running setup.py clean for ninja
  Successfully built meson
  Failed to build ninja
  ERROR: Could not build wheels for ninja which use PEP 517 and cannot be installed directly
  WARNING: You are using pip version 19.2.3, however version 21.1.3 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-_zyrgtxi/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel setuptools_scm 'meson >= 0.48' ninja Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
````

I'm new enough at this that I have no idea how to parse this or what to try next.

**Comment by felipesanches** [comment]
@anthrotype / @m4rc1e, this seems to indicate something broken on the opentype-sanitizer package when building for osx big sur. Any idea what could that be?

**Comment by anthrotype** [comment]
it's trying to build `ninja` from source instead of downloading a pre-compiled wheel package. maybe the ninja maintainer haven't published a pre-compiled wheel for that platform yet.
You said "big sur". Do you know whether it's one of the new macs with the M1 chip?

**Comment by anthrotype** [comment]
Indeed, the list of wheels on ninja's PyPI page currently only has mac wheels for x86_64 architecture, none for arm64 or "universal2" (which includes binaries for both)

https://pypi.org/project/ninja/1.10.0.post2/#files

**Comment by anthrotype** [comment]
this is the relevant issue upstream https://github.com/scikit-build/ninja-python-distributions/issues/41

**Comment by cdeliason** [comment]
My laptop has a 6-Core Intel Core i7.

**Comment by anthrotype** [comment]
> Intel Core i7

hm so it's not about the architecture (as that one is still x86_64).. 🤔

**Comment by anthrotype** [comment]
have you tried to `pip install --upgrade pip` as suggested in the error message?

**Comment by cdeliason** [comment]
Yes and get 
```
zsh: command not found: pip
```

**Comment by cdeliason** [comment]
Okay, now I tried 
pip3 install --upgrade --user pip
and that successfully installed the upgraded pip. 
Then fontbakery installation appears to have worked! 
I do get warnings that all of the installed scripts are in a python bin location that is not on PATH. (and indeed issuing "fontbakery" as a command nets "not found".) What's the "for dummies" explanation for solving that?

**Comment by anthrotype** [comment]
good, closing as solved
