### ISSUE TITLE
Terminal reporter crashes on specific Windows paths with backslashes

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#3750]
## Observed behaviour

Run e.g. `fontbakery check-googlefonts C:\Users\whatever\font.ttf` (should contain hinting) and https://github.com/googlefonts/fontbakery/blob/c222c5e19b2360e20bc769993b21e118b3d59ed4/Lib/fontbakery/reporters/terminal.py#L598 will crash with the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\U'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\somehwere\fontbakery\.venv\Scripts\fontbakery-script.py", line 33, in <module>
    sys.exit(load_entry_point('fontbakery', 'console_scripts', 'fontbakery')())
  File "c:\users\somehwere\fontbakery\lib\fontbakery\cli.py", line 54, in main
    run_profile_check(subcommand_module[6:])
  File "c:\users\somehwere\fontbakery\lib\fontbakery\cli.py", line 27, in run_profile_check
    sys.exit(check_profile_main(module.profile))
  File "c:\users\somehwere\fontbakery\lib\fontbakery\commands\check_profile.py", line 347, in main
    distribute_generator(status_generator, [reporter.receive for reporter in reporters])
  File "c:\users\somehwere\fontbakery\lib\fontbakery\checkrunner.py", line 594, in distribute_generator
    target(item)
  File "c:\users\somehwere\fontbakery\lib\fontbakery\reporters\__init__.py", line 131, in receive
    self._output(event)
  File "c:\users\somehwere\fontbakery\lib\fontbakery\reporters\terminal.py", line 189, in _output
    text = self._render_event(event)
  File "c:\users\somehwere\fontbakery\lib\fontbakery\reporters\terminal.py", line 576, in _render_event
    self._render_event_async(print, event)
  File "c:\users\somehwere\fontbakery\lib\fontbakery\reporters\terminal.py", line 565, in _render_event_async
    self._render_event_sync(print, e)
  File "c:\users\somehwere\fontbakery\lib\fontbakery\reporters\terminal.py", line 464, in _render_event_sync
    formated_msg = parse_md(formated_msg)
  File "c:\users\somehwere\fontbakery\lib\fontbakery\reporters\terminal.py", line 598, in parse_md
    formated_text = re.sub('<#MD-TABLE-'+str(i)+'#>', tables[i], formated_text)
  File "C:\Program Files\Python38\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Program Files\Python38\lib\re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Program Files\Python38\lib\re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Program Files\Python38\lib\sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \U at position 104 (line 1, column 105)
```

Most likely due to the `C:\Users\...` part, where `re` thinks "\U" is an escape sequence. Given that the rendered table is binary gunk, it should probably not be handled by `re` or escape handling in the replacement string should be turned off.

## Expected behaviour

No crash and proper handling of Windows paths.

**Comment by madig** [comment]
Changing the line to `formated_text = formated_text.replace(f'<#MD-TABLE-{i}#>', tables[i], 1)` seems to do the trick.
