### ISSUE TITLE
Local install fails with "setuptools-scm was unable to detect version"

### ISSUE THREAD

**Issue by DavidRaymond** [googlefonts/fontbakery#3776]
I normally keep a locally-installed version of Font Bakery running in developer mode so that I can edit the code to try things out.

The install now fails.

## Observed behaviour
With a clean clone of the main branch, if I install using either of:

- `sudo python3 -m pip install -e .`
- `sudo python3 setup.py develop`

the install fails with:

`LookupError: setuptools-scm was unable to detect version for /home/david/src/fontbakery`

Full trace-back below.

If I comment out the two scm lines in setup-py the install does work - but does not know what version it is!

```$ sudo python3 setup.py develop
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    setup(
  File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 109, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 472, in __init__
    _Distribution.__init__(
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
    self.finalize_options()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 896, in finalize_options
    ep(self)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 917, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/integration.py", line 75, in version_keyword
    _assign_version(dist, config)
  File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/integration.py", line 51, in _assign_version
    _version_missing(config)
  File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/__init__.py", line 106, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /home/david/src/fontbakery.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by DavidRaymond** [comment]
I've tested a bit further, and it does install OK using `sudo python3 -m pip install .`, ie if not in developer mode.

However `sudo python3 setup.py install` still fails.

I've reproduced on a clean Ubuntu 20.04 VM, so it is not something specific to my laptop.

**Comment by felipesanches** [comment]
**sudo** will install it system-wide which should work, even though is not our recommendation, and (as far as I heard) it is not what the most FB developers use on a daily-basis. I prefer (and I know a few other active fontbakery contributors also do prefer) using a virtual environment.

Can you try that to see what happens?

**Comment by DavidRaymond** [comment]
I've tested further and:

- Installing in a virtual environment works OK
- Installing in user mode using `python3 -m pip install --user -e .` works OK

Since installing system-wide is not best practice I don't think this needs further investigation.

On the basis that, since the above commands to work, the version info **is** clearly available from git , it would seem probable that any bugs are in pip or setuptools anyhow!

**Comment by felipesanches** [comment]
thanks
