### ISSUE TITLE
List index out of range (broken progress bar on Windows)

### ISSUE THREAD

**Issue by sacerdesign** [googlefonts/fontbakery#3974]
Maybe my problem is silly. But my little experience is insufficient to understand what is happening. I installed fontbakery on Windows, but when I want to check a font, it shows the following Traceback. I don't know if this is a Python (3.10) install issue or something in fontbakery itself. I've installed and uninstalled different versions of Python before, and this keeps repeating. Does anyone know how to proceed?

**E:\>fontbakery check-googlefonts gara.ttf gara2.ttf**
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\fontbakery.exe\__main__.py", line 7, in <module>
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\cli.py", line 54, in main
    run_profile_check(subcommand_module[6:])
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\cli.py", line 27, in run_profile_check
    sys.exit(check_profile_main(module.profile))
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\commands\check_profile.py", line 352, in main
    distribute_generator(status_generator, [reporter.receive for reporter in reporters])
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\checkrunner.py", line 595, in distribute_generator
    target(item)
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\reporters\__init__.py", line 132, in receive
    self._output(event)
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\reporters\terminal.py", line 189, in _output
    text = self._render_event(event)
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\reporters\terminal.py", line 581, in _render_event
    self._render_event_async(print, event)
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\reporters\terminal.py", line 573, in _render_event_async
    self._render_event_sync(print, event)
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\reporters\terminal.py", line 400, in _render_event_sync
    self.stdout.write(text)
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\reporters\terminal.py", line 125, in write
    self.flush()
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\reporters\terminal.py", line 131, in flush
    progressbar, reset_progressbar = self._draw_progressbar()
  File "C:\Users\myuser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fontbakery\reporters\terminal.py", line 305, in draw_progressbar
    columns = int(columns_entry[0].split()[1])
**IndexError: list index out of range**

**Comment by miguelsousa** [comment]
Seems like a Font Bakery bug. I'll try having a look later today. 
Which version of Font Bakery do you have installed?
Does the problem still happen if you use only one input font?

**Comment by sacerdesign** [comment]
This happens with any number of fonts. For example with:
_fontbakery check-googlefonts gara.ttf
fontbakery check-googlefonts *.ttf_

But everything works with any option: --help, --version, etc.

E:>fontbakery --version
0.8.10

**Comment by sacerdesign** [comment]
The same happens also using venv:
(fontbakery_env) E:\fontbakery_env\Scripts>fontbakery check-googlefonts e:/gara2.ttf
---> equal Traceback

**Comment by miguelsousa** [comment]
Do you mind installing the latest pre-release to see if it makes any difference?

    python -m pip install -U --pre fontbakery

**Comment by sacerdesign** [comment]
Yes... I installed the 0.8.11a5 version and traceback is equal.

**Comment by miguelsousa** [comment]
I'm unable to reproduce this. My versions are:

- Python 3.10.8
- pip 22.3.1 from C:\Users\msousa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip (python 3.10)
- fontbakery 0.8.11a6
- Windows 10 Pro / 20H2 / 19042.1586

**Comment by Kushim-Jiang** [comment]
I meet the same problem from Python 3.11.2, pip 23.0.1, and fontbakery 0.8.11.

```
File "C:\Users\...\AppData\Roaming\Python\Python311\site-packages\fontbakery\reporters\terminal.py", line 400, in _render_event_sync
    self.stdout.write(text)
File "C:\Users\...\AppData\Roaming\Python\Python311\site-packages\fontbakery\reporters\terminal.py", line 125, in write
    self.flush()
File "C:\Users\...\AppData\Roaming\Python\Python311\site-packages\fontbakery\reporters\terminal.py", line 131, in flush
    progressbar, reset_progressbar = self._draw_progressbar()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\...\AppData\Roaming\Python\Python311\site-packages\fontbakery\reporters\terminal.py", line 305, in draw_progressbar
    columns = int(columns_entry[0].split()[1])
                  ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
