### ISSUE TITLE
Several checks not working

### ISSUE THREAD

**Issue by Txonliz** [googlefonts/fontbakery#4001]
**Describe the issue**
While check-opentype works perfectly, other checks are not working (e.g. check-googlefonts, check-adobefonts, check-universal..)

**To Reproduce**
- Install a virtual environment --> python3 -m venv venv  
- Activate environment --> source venv/bin/activate
- Install fontbakery --> pip3 install fontbakery
- Run check in a specific font --> fontbakery check-googlefonts Basati-Regular.otf

**Suggested behavior**
 

**Additional context**
MacBook Pro (14-inch, 2021) Apple M1 Pro Chip
Mac OS Monterey 12.4
zsh command line shell

_Output after check-googlefonts_---->
(venv) macbookpro13@MacBook-Pro-de-Juanlu-2 _Fonts % fontbakery check-googlefonts Basati-Regular.otf          
Traceback (most recent call last):
  File "/Users/juanlu/venv/bin/fontbakery", line 8, in <module>
    sys.exit(main())
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/cli.py", line 54, in main
    run_profile_check(subcommand_module[6:])
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/cli.py", line 26, in run_profile_check
    module = import_module(f"fontbakery.profiles.{profilename}")
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/googlefonts.py", line 3, in <module>
    from fontbakery.profiles.universal import UNIVERSAL_PROFILE_CHECKS
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/universal.py", line 11, in <module>
    from fontbakery.profiles.shaping import SHAPING_PROFILE_CHECKS
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/shaping.py", line 29, in <module>
    from collidoscope import Collidoscope
  File "/Users/juanlu/venv/lib/python3.7/site-packages/collidoscope/__init__.py", line 6, in <module>
    from babelfont import load
ImportError: cannot import name 'load' from 'babelfont' (/Users/juanlu/venv/lib/python3.7/site-packages/babelfont/__init__.py)

_Output after check-adobefonts_ --->
(venv) macbookpro13@MacBook-Pro-de-Juanlu-2 _Fonts % fontbakery check-adobefonts Basati-Regular.otf
Traceback (most recent call last):
  File "/Users/juanlu/venv/bin/fontbakery", line 8, in <module>
    sys.exit(main())
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/cli.py", line 54, in main
    run_profile_check(subcommand_module[6:])
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/cli.py", line 26, in run_profile_check
    module = import_module(f"fontbakery.profiles.{profilename}")
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/adobefonts.py", line 13, in <module>
    from fontbakery.profiles.fontwerk import FONTWERK_PROFILE_CHECKS
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/fontwerk.py", line 10, in <module>
    from fontbakery.profiles.googlefonts import GOOGLEFONTS_PROFILE_CHECKS
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/googlefonts.py", line 3, in <module>
    from fontbakery.profiles.universal import UNIVERSAL_PROFILE_CHECKS
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/universal.py", line 11, in <module>
    from fontbakery.profiles.shaping import SHAPING_PROFILE_CHECKS
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/shaping.py", line 29, in <module>
    from collidoscope import Collidoscope
  File "/Users/juanlu/venv/lib/python3.7/site-packages/collidoscope/__init__.py", line 6, in <module>
    from babelfont import load
ImportError: cannot import name 'load' from 'babelfont' (/Users/juanlu/venv/lib/python3.7/site-packages/babelfont/__init__.py)

_Output after check-universal_ --->
(venv) macbookpro13@MacBook-Pro-de-Juanlu-2 _Fonts % fontbakery check-universal Basati-Regular.otf
Traceback (most recent call last):
  File "/Users/juanlu/venv/bin/fontbakery", line 8, in <module>
    sys.exit(main())
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/cli.py", line 54, in main
    run_profile_check(subcommand_module[6:])
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/cli.py", line 26, in run_profile_check
    module = import_module(f"fontbakery.profiles.{profilename}")
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/universal.py", line 11, in <module>
    from fontbakery.profiles.shaping import SHAPING_PROFILE_CHECKS
  File "/Users/juanlu/venv/lib/python3.7/site-packages/fontbakery/profiles/shaping.py", line 29, in <module>
    from collidoscope import Collidoscope
  File "/Users/juanlu/venv/lib/python3.7/site-packages/collidoscope/__init__.py", line 6, in <module>
    from babelfont import load
ImportError: cannot import name 'load' from 'babelfont' (/Users/juanlu/venv/lib/python3.7/site-packages/babelfont/__init__.py)

**Screenshots**
Screenshot of the last check
![image](https://user-images.githubusercontent.com/10536858/208091029-b67dc4e1-8d70-46ae-ad09-9d996ec2c15a.png)

**Comment by miguelsousa** [comment]
The problem is that the installation is picking up a newer version of **collidoscope**.

I believe you can fix this by either installing a previous version of collidoscope,

    pip3 install collidoscope==0.4.1

or install the latest fontbakery pre-release

    pip3 install -U --pre fontbakery

**Comment by Txonliz** [comment]
Thanks Miguel.
I tried the second option. Everything seems to work now. :-)
