### ISSUE TITLE
--ghmarkdown report not working on Windows

### ISSUE THREAD

**Issue by kenmcd** [googlefonts/fontbakery#4089]
**Describe the issue**
Running fontbakery with the --ghmarkdown report option is no longer working on Windows 10. (for me)

At completion an empty `report.md` file is created.
HTML report works. 
JSON report works.
It (`--ghmarkdown`) was working in an earlier version, but I upgraded and reconfigured (simplified) my python install, and now it is not working.

Cleaned everything out and re-installed clean.
Installed Python 3.11.2 and latest fontbakery 0.8.11.
Markdown report not working - empty file.
HTML and JSON both work.

So I tried going back ...
Also installed Python 3.10.6 and fontbakery 0.8.9.
Markdown report not working - empty file.
HTML and JSON both work.

Tried using command windows with admin privileges - same results. Empty `report.md` file.
Tried multiple different `.ttf` files.
Tried running the fontbakery requirements file again - and it shows all requirements are met.

**To Reproduce**

For Python 3.11.2 and latest fontbakery 0.8.11
`py -m fontbakery check-googlefonts *.ttf --ghmarkdown fontbakery_report.md`

Results in the following:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python311\Lib\site-packages\fontbakery\__main__.py", line 4, in <module>
    fontbakery.cli.main()
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python311\Lib\site-packages\fontbakery\cli.py", line 55, in main
    run_profile_check(subcommand_module[6:])
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python311\Lib\site-packages\fontbakery\cli.py", line 28, in run_profile_check
    sys.exit(check_profile_main(module.profile))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python311\Lib\site-packages\fontbakery\commands\check_profile.py", line 358, in main
    reporter.write()
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python311\Lib\site-packages\fontbakery\reporters\ghmarkdown.py", line 14, in write
    fh.write(self.get_markdown())
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2139' in position 130: character maps to <undefined>
```

For Python 3.10.6 and fontbakery 0.8.9
`py -3.10 -m fontbakery check-googlefonts *.ttf --ghmarkdown fontbakery_report.md`

Results in the following:
```
Traceback (most recent call last):
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\__main__.py", line 4, in <module>
    fontbakery.cli.main()
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\cli.py", line 54, in main
    run_profile_check(subcommand_module[6:])
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\cli.py", line 27, in run_profile_check
    sys.exit(check_profile_main(module.profile))
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\commands\check_profile.py", line 343, in main
    reporter.write()
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\ghmarkdown.py", line 14, in write
    fh.write(self.get_markdown())
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2139' in position 129: character maps to <undefined>
```

**Suggested behavior**
A clear and concise description of what you would like to propose to happen.

I would like the really nice report I had before. :-)

**Additional context**

Hopefully it is just my lack of Python experience and there is a simple fix.
So any guidance would be much appreciated.

If there are some other steps I can do to help debug, please advise.

**Comment by felipesanches** [comment]
https://www.compart.com/en/unicode/U+2139

This is used to represent INFO-level check results.
The problem is that Windows is trying to encode this as CP1252, which won't be possible.
I have now made a change to the code so that it explicitly opens the file using UTF8 encoding.

**Comment by felipesanches** [comment]
I think this has fixed it and will be available on the next pre-release.
For now, you could try to install from git with this command:
`pip install -U git+https://github.com/googlefonts/fontbakery` 

@kenmcd, please let me know if that works for you.

**Comment by kenmcd** [comment]
> For now, you could try to install from git with this command: `pip install -U git+https://github.com/googlefonts/fontbakery`
> 
> @kenmcd, please let me know if that works for you.

Working again.
Thank you!
