### ISSUE TITLE
Crash on  fontbakery-fix-nbsp.py

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#500]
Crash on  fontbakery-fix-nbsp.py
```
$ cd googlefontdirectory/ofl;
$ fontbakery-fix-nbsp.py cwtexfangsong/cwTeXFangSong-zhonly.ttf;
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-fix-nbsp.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.0.5', 'fontbakery-fix-nbsp.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 1436, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/EGG-INFO/scripts/fontbakery-fix-nbsp.py", line 64, in <module>
    fixer.fix(check=True)  # this will print only
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/bakery_cli/fixers.py", line 260, in fix
    spaceWidth = self.getWidth(space)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/bakery_cli/fixers.py", line 246, in getWidth
    return self.font['hmtx'][glyph][0]
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/FontTools/fontTools/ttLib/tables/_h_m_t_x.py", line 98, in __getitem__
    return self.metrics[glyphName]
KeyError: None
$
```

**Comment by davelab6** [comment]
```
$ fontbakery-fix-nbsp.py mergeone/MergeOne-Regular.ttf 
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-fix-nbsp.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.0.5', 'fontbakery-fix-nbsp.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 1436, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/EGG-INFO/scripts/fontbakery-fix-nbsp.py", line 64, in <module>
    fixer.fix(check=True)  # this will print only
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/bakery_cli/fixers.py", line 260, in fix
    spaceWidth = self.getWidth(space)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/bakery_cli/fixers.py", line 246, in getWidth
    return self.font['hmtx'][glyph][0]
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/FontTools/fontTools/ttLib/tables/_h_m_t_x.py", line 98, in __getitem__
    return self.metrics[glyphName]
KeyError: None
$
```

**Comment by davelab6** [comment]
```
$ fontbakery-fix-nbsp.py metrophobic/Metrophobic.ttf 
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-fix-nbsp.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.0.5', 'fontbakery-fix-nbsp.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 1436, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/EGG-INFO/scripts/fontbakery-fix-nbsp.py", line 64, in <module>
    fixer.fix(check=True)  # this will print only
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/bakery_cli/fixers.py", line 260, in fix
    spaceWidth = self.getWidth(space)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/bakery_cli/fixers.py", line 246, in getWidth
    return self.font['hmtx'][glyph][0]
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/FontTools/fontTools/ttLib/tables/_h_m_t_x.py", line 98, in __getitem__
    return self.metrics[glyphName]
KeyError: None
```
