### ISSUE TITLE
TypeError: coercing to Unicode

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#520]
```
$ git clone https://github.com/google/fonts.git;
$ cd fonts/ofl/vesperlibre/;
$ fontbakery-check.py '*' *ttf;
```

Output is
```
$ mv VesperLibre-Bold.ttf.fix VesperLibre-Bold.ttf
$ mv VesperLibre-Bold.ttf.fix VesperLibre-Bold.ttf
$ mv VesperLibre-Bold.ttf.fix VesperLibre-Bold.ttf
$ mv VesperLibre-Bold.ttf.fix VesperLibre-Bold.ttf
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-check.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.0.5', 'fontbakery-check.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 1436, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/EGG-INFO/scripts/fontbakery-check.py", line 58, in <module>
    result = run_set(x, test)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontbakery-0.0.5-py2.7.egg/bakery_lint/__init__.py", line 25, in run_set
    assert os.path.exists(path), '%s does not exists' % path
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, FontForgeValidateStateTest found
$
```

**Comment by vitalyvolkov** [comment]
Please check
