### ISSUE TITLE
fontbakery-fix-vertical-metrics.py crash

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#551]
```
$ git clone git@github.com:davelab6/bootstrap-winjs.git ; 
$ cd bootstrap-winjs/src/fonts ;
$ fontbakery-fix-vertical-metrics.py *ttf ;
... ok :) ...
$ fontbakery-fix-vertical-metrics.py --autofix *ttf ;
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-fix-vertical-metrics.py", line 5, in <module>
    pkg_resources.run_script('fontbakery==0.0.10', 'fontbakery-fix-vertical-metrics.py')
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources/__init__.py", line 723, in run_script
    
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources/__init__.py", line 1636, in run_script
    
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.10-py2.7.egg/EGG-INFO/scripts/fontbakery-fix-vertical-metrics.py", line 128, in <module>
    fixer.apply(ymin, ymax)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.10-py2.7.egg/bakery_cli/fixers.py", line 72, in apply
    self.save()
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.10-py2.7.egg/bakery_cli/fixers.py", line 62, in save
    self.font.save(self.fixfont_path)
  File "build/bdist.macosx-10.9-intel/egg/fontTools/ttLib/__init__.py", line 214, in save
    
  File "build/bdist.macosx-10.9-intel/egg/fontTools/ttLib/__init__.py", line 629, in _writeTable
    
  File "build/bdist.macosx-10.9-intel/egg/fontTools/ttLib/__init__.py", line 642, in getTableData
    
  File "build/bdist.macosx-10.9-intel/egg/fontTools/ttLib/tables/_c_m_a_p.py", line 66, in compile
  File "build/bdist.macosx-10.9-intel/egg/fontTools/ttLib/tables/_c_m_a_p.py", line 865, in compile
IndexError: list index out of range
$
```

**Comment by vitalyvolkov** [comment]
Not sure that this is fontbakery issue, but may be I am using fontTools wrong.

```
#!/usr/bin/env python
# coding: utf-8
from fontTools.ttLib import TTFont


def main():
	ttfont = TTFont('winjs-symbols.ttf')
	ttfont['hhea'].ascent = 1178
	# ttfont['OS/2'].usWinAscent = int(1178)
	# ttfont['OS/2'].sTypoAscender = int(1178)
	ttfont.save('1.ttf')

main()
```

If you run this script with font then you will get no errors but

```
#!/usr/bin/env python
# coding: utf-8
from fontTools.ttLib import TTFont


def main():
	ttfont = TTFont('winjs-symbols.ttf')
	ttfont['hhea'].ascent = 1178
	ttfont['OS/2'].usWinAscent = int(1178)
	# ttfont['OS/2'].sTypoAscender = int(1178)
	ttfont.save('1.ttf')

main()
```

This code is raising exception. May be someone know what's wrong with it? @behdad @davelab6

**Comment by anthrotype** [comment]
What exception do you get exactly? I don't see anything wrong with the latter snippet (apart from `int(1178)` which is redundant)

**Comment by vitalyvolkov** [comment]
yeah, int is reduntant, dont worry with it :)

```
  File "vmet.py", line 13, in <module>
    main()
  File "vmet.py", line 11, in main
    ttfont.save('1.ttf')
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 214, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 629, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 642, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/_c_m_a_p.py", line 66, in compile
    chunk = table.compile(ttFont)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/_c_m_a_p.py", line 865, in compile
    firstCode = codes[0]
IndexError: list index out of range
```

**Comment by anthrotype** [comment]
Compiling cmap doesn't have anything to do with vertical metrics...
Did you say the first snippet where the usWinAscent line is commented out doesn't raise the exception?
Does it occur with other fonts as well?

**Comment by vitalyvolkov** [comment]
Does not happen with another fonts. Strange, why that error is raised?

**Comment by vitalyvolkov** [comment]
> Compiling cmap doesn't have anything to do with vertical metrics...

So in this case we have to create those rules in cmap. Is that right, @davelab6 ?

**Comment by anthrotype** [comment]
It happens maybe because the cmap subtable format 6 is empty and so it raises index error.
Are you using the latest HEAD from behdad's fontTools?

**Comment by vitalyvolkov** [comment]
> Are you using the latest HEAD from behdad's fontTools?
yes

**Comment by vitalyvolkov** [comment]
How `cmap` table related to vertical metrics?

**Comment by anthrotype** [comment]
the reason the cmap table is being re-compiled after you modify the OS/2 table has nothing to do with vertical metrics. It's because fontTools updates the OS/2 `usFirstCharIndex` and `usLastCharIndex` values, and to do that it first needs to decompile the cmap table to get all the character codes.

There seems to be an issue with the way the cmap subtable format 6 is compiled. I'll have a look and let you know.

**Comment by anthrotype** [comment]
it should be fixed with https://github.com/behdad/fonttools/commit/e05db5c75f8be0a9364a10e754059ff95527b920
Please let me know if it works now.

**Comment by davelab6** [comment]
@anthrotype :elephant:

**Comment by vitalyvolkov** [comment]
@anthrotype it works. @davelab6 please check :)
