### ISSUE TITLE
fontbakery-setup.py crash

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#552]
```
mkdir -p ~/src/github.com/10four/ ;
cd ~/src/github.com/10four/ ;
git clone git@github.com:10four/Bhavuka.git ;
cd Bhavuka;
fontbakery-setup.py . ;

WARNING: Please install PyICU <https://pypi.python.org/pypi/PyICU> to enable CLDR related features, perhaps with: pip install pyicu
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-setup.py", line 5, in <module>
    pkg_resources.run_script('fontbakery==0.0.10', 'fontbakery-setup.py')
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources/__init__.py", line 723, in run_script
    
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources/__init__.py", line 1636, in run_script
    
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.10-py2.7.egg/EGG-INFO/scripts/fontbakery-setup.py", line 273, in <module>
    subsets = generate_subsets_coverage_list()
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.10-py2.7.egg/EGG-INFO/scripts/fontbakery-setup.py", line 211, in generate_subsets_coverage_list
    return get_subsets_coverage_data(source_fonts_paths)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.10-py2.7.egg/EGG-INFO/scripts/fontbakery-setup.py", line 189, in get_subsets_coverage_data
    font = FontFactory.openfont(fontpath)
  File "/usr/local/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg/fontaine/font.py", line 136, in openfont
    return TTFont(fontfile, charmaps)
  File "/usr/local/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg/fontaine/font.py", line 213, in __init__
    self._fontFace = FontFace(fontfile)
  File "/usr/local/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg/fontaine/font.py", line 47, in __init__
    self.ttf = ttLib.TTFont(fontfile, fontNumber=1)
  File "build/bdist.macosx-10.9-intel/egg/fontTools/ttLib/__init__.py", line 168, in __init__
    
  File "build/bdist.macosx-10.9-intel/egg/fontTools/ttLib/sfnt.py", line 70, in __init__
fontTools.ttLib.TTLibError: Not a TrueType or OpenType font (bad sfntVersion)
```

**Comment by sladen** [comment]
ICU == International Components for Unicode
* https://pypi.python.org/pypi/PyICU
CLDR == Unicode Common Locale Data Repository
* http://cldr.unicode.org/

**Comment by davelab6** [comment]
yep :)

**Comment by vitalyvolkov** [comment]
I bumped 0.0.11 version for you, in it fontbakery-setup.py is not crashed when you run it.
