### ISSUE TITLE
AttributeError: 'CharmapInfo' object has no attribute 'charset'

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#557]
```
~$ mkdir tmp;
$ cd tmp;
$ git clone http://github.com/itfoundry/kalam.git;
$ cd kalam;
$ ls build;
Kalam-Bold.otf Kalam-Light.otf Kalam-Regular.otf
$ fontbakery-setup.py . ;
WARNING: Please install PyICU <https://pypi.python.org/pypi/PyICU> to enable CLDR related features, perhaps with: pip install pyicu
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-setup.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.0.11', 'fontbakery-setup.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.11-py2.7.egg/EGG-INFO/scripts/fontbakery-setup.py", line 277, in <module>
    subsets = generate_subsets_coverage_list()
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.11-py2.7.egg/EGG-INFO/scripts/fontbakery-setup.py", line 215, in generate_subsets_coverage_list
    return get_subsets_coverage_data(source_fonts_paths)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.11-py2.7.egg/EGG-INFO/scripts/fontbakery-setup.py", line 196, in get_subsets_coverage_data
    subsetname = info.charset.common_name.replace('Subset ', '')
AttributeError: 'CharmapInfo' object has no attribute 'charset'
$
```

**Comment by davelab6** [comment]
Fixed by installing pyfontaine from git master
