### ISSUE TITLE
ImportError: cannot import name quadopt

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#558]
```
~$ mkdir tmp;
$ cd tmp;
$ git clone http://github.com/itfoundry/kalam.git;
$ cd kalam;
$ ls build;
Kalam-Bold.otf Kalam-Light.otf Kalam-Regular.otf
$ fontbakery-setup.py . ;
$ fontbakery-build.py . ;
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-build.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.0.11', 'fontbakery-build.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.11-py2.7.egg/EGG-INFO/scripts/fontbakery-build.py", line 33, in <module>
    from bakery_cli.bakery import Bakery, BAKERY_CONFIGURATION_DEFAULTS
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.11-py2.7.egg/bakery_cli/bakery.py", line 22, in <module>
    from bakery_cli import pipe
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.11-py2.7.egg/bakery_cli/pipe/__init__.py", line 14, in <module>
    from bakery_cli.pipe.font_crunch import FontCrunch
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.11-py2.7.egg/bakery_cli/pipe/font_crunch.py", line 20, in <module>
    from fontcrunch import fontcrunch
  File "/Library/Python/2.7/site-packages/fontcrunch/__init__.py", line 1, in <module>
    from .fontcrunch import optimize
  File "/Library/Python/2.7/site-packages/fontcrunch/fontcrunch.py", line 26, in <module>
    from . import quadopt
ImportError: cannot import name quadopt
$
```

**Comment by davelab6** [comment]
Seems like this is a problem upstream, as this doesn't work:
```
from fontcrunch import fontcrunch
```
