### ISSUE TITLE
PyFontaine Checks No Longer Working

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#594]
```
felipe@guarana:~/devel/github_felipesanches/CoinyTests$ fontbakery-report.py builds/2753ec6/
Copying file: /home/felipe/devel/github_felipesanches/CoinyTests/builds/2753ec6/Coiny-Regular2911.ttf -> builds/2753ec6/build_info/static/css/fonts
Build info added.
[builds/2753ec6/]:git log -n1 --pretty=format:'{"hash":"%h", "commit":"%H","date":"%cd"}'
Dumping data to file: build_info.json
Dumping data to file: repo.json
Writing data to file: builds/2753ec6/index.html
Writing data to file: builds/2753ec6/README.md
Dumping data to file: builds/2753ec6/build_info/data/pages/tests/tests.json
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
Dumping data to file: builds/2753ec6/build_info/data/pages/summary/metrics.json
Dumping data to file: builds/2753ec6/build_info/data/pages/summary/stems.json
Dumping data to file: builds/2753ec6/build_info/data/pages/summary/table_sizes.json
Dumping data to file: builds/2753ec6/build_info/data/pages/summary/autohint_sizes.json
Dumping data to file: builds/2753ec6/build_info/data/pages/summary/tests.json
Dumping data to file: builds/2753ec6/build_info/data/pages/summary/fonts_tables_grouped.json
Writing data to file: builds/2753ec6/build_info/static/css/faces.css
Dumping data to file: builds/2753ec6/build_info/data/pages/summary/fontaine_fonts.json
WARNING: Please install PyICU <https://pypi.python.org/pypi/PyICU> to enable CLDR related features, perhaps with: pip install pyicu
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-report.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.0.12', 'fontbakery-report.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/fontbakery-0.0.12-py2.7.egg/EGG-INFO/scripts/fontbakery-report.py", line 46, in <module>
    index.generate(config)
  File "/usr/local/lib/python2.7/dist-packages/fontbakery-0.0.12-py2.7.egg/bakery_cli/report/index.py", line 304, in generate
    fonts_orthography = get_orthography(fonts)
  File "/usr/local/lib/python2.7/dist-packages/fontbakery-0.0.12-py2.7.egg/bakery_cli/report/index.py", line 182, in get_orthography
    fonts_dict[info.charmap.common_name].append(font_info)
AttributeError: 'CharsetInfo' object has no attribute 'charmap'
```

**Comment by felipesanches** [comment]
Due to this error, I have temporarily disable this portion of the code. We need to adapt it to the new method signature in fontaine and then re-enable it.

**Comment by felipesanches** [comment]
@davelab6 This was the commit that temporarily disabled the broken code: a9d2ece435d57a30ea59db55525c6943078f1631

**Comment by davelab6** [comment]
0.1.0 should run pyfontaine checks

**Comment by davelab6** [comment]
@felipesanches what is the status of this?

**Comment by davelab6** [comment]
@felipesanches I think the next step is to run pyfontaine via its command line interface, since it seems the internal python API is not stable/reliable; that will also make it easier for me to make PRs changing what it checks myself. 

Here is a pass - no 'Missing' appears in the text:

```
$ pyfontaine --missing --set gwf_latin ~/fonts/apache/arimo/Arimo-Regular.ttf 
WARNING: Please install PyICU <https://pypi.python.org/pypi/PyICU> to enable CLDR related features, perhaps with: pip install pyicu
Fonts
  Font:
    Filename: Arimo-Regular.ttf
    Common name: Arimo
    Sub family: Regular
    Weight: normal
    Fixed width: no
    Fixed sizes: no
    Copyright: Digitized data copyright (c) 2010-2012 Google Corporation.
    License: Licensed under the Apache License, Version 2.0
    License url: http://www.apache.org/licenses/LICENSE-2.0
    Version: Version 1.23
    Vendor: Monotype Imaging Inc.
    Vendor url: http://www.monotypeimaging.com
    Designer: Steve Matteson
    Designer url: http://www.monotypeimaging.com/ProductsServices/TypeDesignerShowcase
    Glyph count: 2584
    Character count: 2302
    Orthographies:
        Orthography:
          Common name: Google latin
          Support level: full
$
```

Here are some warnings, with 'partial' support: 

```
$ pyfontaine --missing --set gwf_latin ~/fonts/ofl/merriweathersans/MerriweatherSans-Regular.ttf 
WARNING: Please install PyICU <https://pypi.python.org/pypi/PyICU> to enable CLDR related features, perhaps with: pip install pyicu
Fonts
  Font:
    Filename: MerriweatherSans-Regular.ttf
    Common name: Merriweather Sans
    Sub family: Regular
    Weight: normal
    Fixed width: no
    Fixed sizes: no
    Copyright: Copyright (c) 2013-2016, Sorkin Type Co (www.sorkintype.com) with Reserved Font Name 'Merriweather'
    License: This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
    License url: http://scripts.sil.org/OFL
    Version: Version 1.006; ttfautohint (v1.4.1) -l 6 -r 50 -G 0 -x 11 -H 220 -D latn -f none -w "" -X ""
    Vendor: Eben Sorkin
    Vendor url: sorkintype.com
    Designer: Eben Sorkin
    Designer url: sorkintype.com
    Glyph count: 481
    Character count: 452
    Orthographies:
        Orthography:
          Glyphs in set: 214
          Glyphs in font: 212
          Percent coverage: 99
          Missing values: 
              U+00ad  ­  SOFT HYPHEN
              U+00ad  ­  SOFT HYPHEN
          Common name: Google latin
          Support level: partial
$ pyfontaine --missing --set gwf_latin ~/fonts/ofl/merriweather/Merriweather-Regular.ttf 
WARNING: Please install PyICU <https://pypi.python.org/pypi/PyICU> to enable CLDR related features, perhaps with: pip install pyicu
Fonts
  Font:
    Filename: Merriweather-Regular.ttf
    Common name: Merriweather
    Sub family: Regular
    Weight: normal
    Fixed width: no
    Fixed sizes: no
    Copyright: Copyright (c) 2010-2016, Sorkin Type Co (www.sorkintype.com) with Reserved Font Name 'Merriweather'
    License: This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
    License url: http://scripts.sil.org/OFL
    Version: Version 1.584; ttfautohint (v1.5) -l 6 -r 36 -G 0 -x 10 -H 350 -D latn -f cyrl -w "" -X ""
    Vendor: Eben Sorkin
    Vendor url: sorkintype.com
    Designer: Eben Sorkin
    Designer url: sorkintype.com
    Glyph count: 729
    Character count: 693
    Orthographies:
        Orthography:
          Glyphs in set: 214
          Glyphs in font: 210
          Percent coverage: 98
          Missing values: 
              U+00b2  ²  SUPERSCRIPT TWO
              U+00b3  ³  SUPERSCRIPT THREE
              U+00b9  ¹  SUPERSCRIPT ONE
              U+2074  ⁴  SUPERSCRIPT FOUR
          Common name: Google latin
          Support level: partial
$
```

If `Support level: full` isn't in the output then the entire output should be reported
