### ISSUE TITLE
fontbakery-fix-version.py

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#660]
- [ ] We should test that the version in `head.fontRevision` and in the `name` table are greater than 1.0 as some systems will reject fonts with a version less than this
- [ ] It would be great to be able to set alphanumeric version numbers, like this:

```
fontbakery-fix-version.py --set 3.000g raleway/Raleway-Regular.ttf 
new_version is: 3.000g
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-fix-version.py", line 4, in <module>
    __import__('pkg_resources').run_script('fontbakery==0.0.13', 'fontbakery-fix-version.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.13-py2.7.egg/EGG-INFO/scripts/fontbakery-fix-version.py", line 39, in <module>
    fixer.apply(options)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.13-py2.7.egg/bakery_cli/fixers.py", line 65, in apply
    if not self.fix(*args, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.13-py2.7.egg/bakery_cli/fixers.py", line 173, in fix
    self.set_new_version(options.set[0])
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.13-py2.7.egg/bakery_cli/fixers.py", line 150, in set_new_version
    self.font['head'].fontRevision = self.get_version_fields(str(self.font['head'].fontRevision), new_value, head_table=True)
  File "/usr/local/lib/python2.7/site-packages/fontbakery-0.0.13-py2.7.egg/bakery_cli/fixers.py", line 145, in get_version_fields
    return float(new_version)
ValueError: invalid literal for float(): 3.000g
```

What should happen in this case is that if the `--set` arg is passed a string that passes the regex

```
$float + string
```

then the string should be used in the `name` table entries and the float only in the `head`.

**Comment by felipesanches** [comment]
migrated to https://github.com/googlefonts/tools/issues/20
