### ISSUE TITLE
investigate BLACKLISTED: SystemError: tile cannot extend outside image

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#704]
blacklisted on font_compare_metrics.py (Issue #684)
- Suwannaphum
- KarlaTamil
- Khmer
- KdamThmor
- Battambang
- AksaraBaliGalang
- Phetsarath
- Kantumruy
- Nokora
- Droid

```
fontfile: '../../github_google/fonts/ofl/suwannaphum/Suwannaphum.ttf'
Traceback (most recent call last):
  File "tools/compute_font_metrics.py", line 268, in <module>
    main()
  File "tools/compute_font_metrics.py", line 126, in main
    properties.append(get_width(fontfile))
  File "tools/compute_font_metrics.py", line 222, in get_width
    return {'value': text_width, 'fontfile': fontfile, 'base64img': get_base64_image(img)}
  File "tools/compute_font_metrics.py", line 255, in get_base64_image
    img.save(output, "PNG")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1468, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python2.7/dist-packages/PIL/PngImagePlugin.py", line 624, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0,0)+im.size, 0, rawmode)])
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 462, in _save
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image
```

**Comment by davelab6** [comment]
I guess this is because its trying to draw characters that do not exist in the font

**Comment by felipesanches** [comment]
same error for "KarlaTamilUpright":

```
fontfile: '../../github_google/fonts/ofl/karlatamilupright/KarlaTamilUpright-Regular.ttf'
```

**Comment by felipesanches** [comment]
well... 
KarlaTamil in general

```
fontfile: '../../github_google/fonts/ofl/karlatamilinclined/KarlaTamilInclined-Bold.ttf'
```

As well as Khmer:

```
fontfile: '../../github_google/fonts/ofl/khmer/Khmer.ttf'
```

**Comment by felipesanches** [comment]
I'll simply add all of them to the issue description on the top.

```
fontfile: '../../github_google/fonts/ofl/kdamthmor/KdamThmor-Regular.ttf'
```

**Comment by felipesanches** [comment]
Migrating to Google Fonts Tools repo
