### ISSUE TITLE
fontbakery-build.py fails on KeyError: 'subset'

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#764]
@felipesanches fontbakery-build.py recently regressed and now fails with `KeyError: 'subset'` - I guess this was introduced by your recent changes to remove subsets from the whole thing.

```
BUILD FAILED
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-build.py", line 113, in <module>
    run_bakery(os.path.abspath(p), verbose=args.verbose)
  File "/usr/local/bin/fontbakery-build.py", line 85, in run_bakery
    b.run()
  File "/usr/local/lib/python2.7/dist-packages/bakery_cli/bakery.py",
line 140, in run
    return self.normal_run(self.pipes)
  File "/usr/local/lib/python2.7/dist-packages/bakery_cli/bakery.py",
line 161, in normal_run
    p.execute(self.config)
  File "/usr/local/lib/python2.7/dist-packages/bakery_cli/pipe/upstreamlint.py",
line 41, in execute
    result['Project'] = run_set(upstreamdir, 'upstream-repo')
  File "/usr/local/lib/python2.7/dist-packages/bakery_lint/__init__.py",
line 26, in run_set
    tests_suite = make_suite(path, target, test_method=test_method,
apply_fix=apply_fix, log=log)
  File "/usr/local/lib/python2.7/dist-packages/bakery_lint/base.py",
line 310, in make_suite
    TestCase.__generateTests__()
  File "/usr/local/lib/python2.7/dist-packages/bakery_lint/fonttests/test_upstream.py",
line 271, in __generateTests__
    if shortname not in bakerydata['subset']:
KeyError: 'subset'
```

**Comment by davelab6** [comment]
cc @girish-dalvi

**Comment by davelab6** [comment]
For now, Font Bakery is no longer a build tool; if you want to access the old versions, install them from pypi with pip; current development is focused on simple imperative 'lint' script in a single file :)
