### ISSUE TITLE
Script should be self contained

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#768]
fontbakery-check-ttf.py should be simple and that means self contained: Few methods, and zerp external files.

```
$ python ~/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py fonts/apache/cousine/Cousine-*ttf;
INFO     OK: fonts/apache/cousine/Cousine-Bold.ttf is named canonically  
INFO     OK: fonts/apache/cousine/Cousine-BoldItalic.ttf is named canonically  
INFO     OK: fonts/apache/cousine/Cousine-Italic.ttf is named canonically  
INFO     OK: fonts/apache/cousine/Cousine-Regular.ttf is named canonically  
INFO     Starting new HTTPS connection (1): www.microsoft.com  
INFO     OK: fonts/apache/cousine/Cousine-Bold.ttf opened with fontTools  
ERROR    HOTFIXED: fsType is zero. Fixes: OS/2 fsType from 8 to 0  
INFO     OK: OS/2 VendorID is 'MONO' and registered to 'Monotype Imaging'. Is that legit?  
INFO     OK: OS/2 usWeightClass  
INFO     OK: fsSelection REGULAR bit  
INFO     OK: italicAngle <= 0  
INFO     OK: matching of fontstyle and italicAngle value  
INFO     OK: fsSelection ITALIC bit  
ERROR    HOTFIXED: macStyle ITALIC bit Fixes: head macStyle from 1 to 0  
INFO     OK: fsSelection BOLD bit  
ERROR    HOTFIXED: macStyle BOLD bit Fixes: head macStyle from 0 to 1  
INFO     OK: Found license at 'fonts/apache/cousine/LICENSE.txt'  
Traceback (most recent call last):
  File "/Users/dcrossland/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py", line 739, in <module>
    main()
  File "/Users/dcrossland/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py", line 448, in main
    placeholder = open(PLACEHOLDER_FILENAMES[license]).read().strip()
IOError: [Errno 2] No such file or directory: 'Data/OFL.placeholder'
```

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/blob/v0.1.0/fontbakery-check-ttf.py#L8

**Comment by sladen** [comment]
First step would be to remove the "import *", and then the namespacing becomes clear, and then the import can be moved to where-ever it is actually being used, inside a **try:** so that things fail gracefully.

**Comment by davelab6** [comment]
@sladen I think its better to have all imports at the top so that if you don't have the requirements installed, you find that fact up front, rather than when you are in the middle of working.

**Comment by felipesanches** [comment]
@davelab6  So you want the nameID definitions to be embedded in the single script as well? I can do it, no problem :-)

**Comment by davelab6** [comment]
Of course.

**Comment by felipesanches** [comment]
alright! :-D
