### ISSUE TITLE
'unicode' object has no attribute 'platformID'

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#793]
```
Traceback (most recent call last):
  File "/Users/dcrossland/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py", line 1999, in <module>
    main()
  File "/Users/dcrossland/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py", line 1326, in main
    elif (familyname.platformID == fullfontname.platformID
AttributeError: 'unicode' object has no attribute 'platformID'
```

**Comment by davelab6** [comment]
I commented the code block and got
```
Traceback (most recent call last):
  File "/Users/dcrossland/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py", line 1999, in <module>
    main()
  File "/Users/dcrossland/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py", line 1712, in main
    logging.err("METADATA.pb name='{}' does not match correct font name format.".format(f.name))
AttributeError: 'module' object has no attribute 'err'
```

**Comment by davelab6** [comment]
There are occurences of `logging.err(` that should be `logging.error(`

**Comment by felipesanches** [comment]
The "logging.err(" occurrences as well as the unicode.platformID were not detected by the linter and also not reached by the Cousine font I was using to test this code.

I'll fix the typos and temporarily disable the broken test before I properly fix the test implementation.

**Comment by felipesanches** [comment]
I fixed it at https://github.com/googlefonts/fontbakery/commit/6a1baa602e7485942bbe52f86e12bfc66913d3e6
