### ISSUE TITLE
Memory Error when running check-ttf on AbyssinicaSIL

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#809]
```bash
felipe@guarana:~/devel/github_google/fonts/ofl/abyssinicasil$ ~/devel/github_felipesanches/fontbakery/fontbakery-check-ttf.py *.ttf -v
INFO     OK: AbyssinicaSIL-Regular.ttf is named canonically  
INFO     OK: Font designer field ('SIL International') is not 'unknown'.  
INFO     OK: Fonts have equal numbers of glyphs.  
INFO     OK: Fonts have equal glyph names.  
INFO     OK: Fonts have equal unicode encodings.  
INFO     OK: AbyssinicaSIL-Regular.ttf opened with fontTools  
INFO     OK: fsType is zero.  
WARNING  VendorID string 'SIL International (SIL)' does not match nameID 8 (Manufacturer Name): 'SIL International'  
WARNING  VendorID string 'SIL International (SIL)' does not match nameID 8 (Manufacturer Name): 'SIL International'  
INFO     OK: OS/2 VendorID is 'SIL ' and registered to 'SIL International (SIL)'. Is that legit?  
INFO     OK: No need to substitute copyright, registered and trademark symbols in name table entries of this font.  
INFO     OK: OS/2 usWeightClass  
INFO     OK: fsSelection REGULAR bit  
INFO     OK: post table italicAngle is 0.0  
INFO     OK: OK: post table italicAngle is less than 20 degrees.  
INFO     OK: post table italicAngle matches style name  
INFO     OK: fsSelection ITALIC bit  
INFO     OK: macStyle ITALIC bit  
INFO     OK: fsSelection BOLD bit  
INFO     OK: macStyle BOLD bit  
INFO     OK: Found license at 'OFL.txt'  
INFO     HOTFIXED: License file OFL.txt exists but NameID value is not specified for that.  
INFO     HOTFIXED: License file OFL.txt exists but NameID value is not specified for that.  
INFO     HOTFIXED: some name table items with platformID=1 were removed  
INFO     HOTFIXED: Namerecord 10s (descriptions) were removed (perhaps added by a longstanding FontLab Studio 5.x bug.)  
INFO     HOTFIXED: AbyssinicaSIL-Regular.ttf: Windows-only Opentype-specific StyleName set to "Regular".  
Traceback (most recent call last):
  File "/home/felipe/devel/github_felipesanches/fontbakery/fontbakery-check-ttf.py", line 2672, in <module>
    main()
  File "/home/felipe/devel/github_felipesanches/fontbakery/fontbakery-check-ttf.py", line 1057, in main
    new_names.append(entry)
MemoryError
^C^C^C^C^C^C^C
```

**Comment by felipesanches** [comment]
fixed it.

**Comment by davelab6** [comment]
🎱
