### ISSUE TITLE
Alef-Regular.ttf: regex.match(license_url): TypeError: expected string or buffer

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#812]
```
./fontbakery-check-ttf.py ~/devel/github_google/fonts/ofl/alef/*.ttf -v
```

```
INFO     OK: None of the ASCII-only NAME table entries contain non-ASCII characteres.  
Traceback (most recent call last):
  File "./fontbakery-check-ttf.py", line 2678, in <module>
    main()
  File "./fontbakery-check-ttf.py", line 1931, in main
    if not regex.match(license_url):
TypeError: expected string or buffer
```

**Comment by felipesanches** [comment]
fixed at 7957b2e3bf1312a02ae2fe4ae926c45e0bbe9d70
