### ISSUE TITLE
AlegreyaSansSC-*.ttf: AttributeError: PairSetCount

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#813]
```
./fontbakery-check-ttf.py ~/devel/github_google/fonts/ofl/alegreyasanssc/*.ttf -v
```

```
INFO     OK: GASP table is correctly set.  
Traceback (most recent call last):
  File "./fontbakery-check-ttf.py", line 2679, in <module>
    main()
  File "./fontbakery-check-ttf.py", line 1691, in main
    elif flaglookup.SubTable[0].PairSetCount == 0:
  File "/home/felipe/devel/github_felipesanches/scope-one/src/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 570, in __getattr__
    raise AttributeError(attr)
AttributeError: PairSetCount
```

**Comment by felipesanches** [comment]
fixed at https://github.com/googlefonts/fontbakery/commit/f907c41c44a947d8fc0aaaece78baffdd2c75ef4
