### ISSUE TITLE
Allan-Bold.ttf: UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#814]
```
./fontbakery-check-ttf.py ~/devel/github_google/fonts/ofl/allan/*.ttf -v
```

```
INFO     OK: fsType is zero.  
Traceback (most recent call last):
  File "./fontbakery-check-ttf.py", line 2681, in <module>
    main()
  File "./fontbakery-check-ttf.py", line 722, in main
    registered_vendor_ids[vid]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)
```

**Comment by felipesanches** [comment]
fixed at 8afafffed50d61411b6a31384ce7c6f813e3db65
