### ISSUE TITLE
DuruSans-Regular.ttf: UnicodeEncodeError

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#815]
when running chech-ttf on DuruSans-Regular.ttf, I got:

```
DEBUG    Check #7: Checking OS/2 achVendID  
Traceback (most recent call last):
  File "./fontbakery-check-ttf.py", line 2684, in <module>
    main()
  File "./fontbakery-check-ttf.py", line 720, in main
    manufacturer))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf5' in position 8: ordinal not in range(128)
```

**Comment by felipesanches** [comment]
fixed at d4258ef4d6ea927315ef2f72e1786fa0729c1136
