### ISSUE TITLE
fb-check-ttf.py: Test for each dependency at the start of the script

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/fontbakery#860]
Did a fresh install on OS X 10.11.5, and I get this error. 
I am missing something?

```
[~]-------> fontbakery-check-ttf.py /Users/alexei/github.com/cyrealtype/Lora-Cyrillic/Lora-Regular.ttf 
ERROR    '/Users/alexei/github.com/cyrealtype/Lora-Cyrillic/Lora-Regular.ttf' is missing a METADATA.pb file!  
ERROR    OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx  
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
Warning: Mac string is a subset of the Windows string in the 'name' table
 for the Fullname string in the English (US) language.
Traceback (most recent call last):
  File "/usr/local/bin/fontbakery-check-ttf.py", line 3064, in <module>
    main()
  File "/usr/local/bin/fontbakery-check-ttf.py", line 1874, in main
    dehinted.name])
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by anthrotype** [comment]
Hey Alexey!
try `brew install ttfautohint`

**Comment by davelab6** [comment]
@felipesanches I thought we had checks at the very start of the script that tested for the presence of all dependencies, but now all I see is

https://github.com/googlefonts/fontbakery/blob/ced628d4af8b7db22f9bc348efd46721fddaeedb/fontbakery-check-ttf.py#L33-L36

**Comment by alexeiva** [comment]
@anthrotype 
Hi Cosimo! 

> try brew install ttfautohint

Thank you, that actually worked for me.

**Comment by felipesanches** [comment]
We don't do it on the top.
We do check at runtime, such as here (checking if ot-sanitize is available):

https://github.com/googlefonts/fontbakery/blob/b4691fb581d545749b4b955c096506d5e5c9b9cd/fontbakery-check-ttf.py#L1503-L1510

I'll use the same approach for the availability of ttfautohint

**Comment by davelab6** [comment]
Since you closed this please confirm that all dependencies are now checked.
