### ISSUE TITLE
fontbakery-build-fontmetadata.py fails if it can't find a pre-existing images directory

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#923]
We should check if the image folder exists and, if not, create it.

```
felipe@guarana:~/devel/github_felipesanches/fontbakery$ python test_args.py 
Traceback (most recent call last):
  File "test_args.py", line 29, in <module>
    target = __import__(module_name)
  File "/home/felipe/devel/github_felipesanches/fontbakery/fontbakery-build-fontmetadata.py", line 143, in <module>
    generate_italic_angle_images()
  File "/home/felipe/devel/github_felipesanches/fontbakery/fontbakery-build-fontmetadata.py", line 141, in generate_italic_angle_images
    im.save(filepath, "PNG")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1462, in save
    fp = builtins.open(fp, "wb")
IOError: [Errno 2] No such file or directory: '/home/felipe/devel/github_felipesanches/fontbakery/fontmetadata_tool/images/angle_1.png'
```

**Comment by felipesanches** [comment]
https://github.com/googlefonts/fontbakery/issues/922 depends on fixing this.

**Comment by davelab6** [comment]
fontbakery-build-fontmetadata.py is no longer actively needed; don't delete
it but don't work on it :)

**Comment by felipesanches** [comment]
well... I just fixed it. I'll merge the fix and leave it alono then :-)
