### ISSUE TITLE
Too many values to unpack on a split(";")

### ISSUE THREAD

**Issue by vmesel** [googlefonts/fontbakery#954]
When trying to run the fontbakery in verbose mode with the Carlito Font(https://fontlibrary.org/en/font/carlito), there is an error output:

```
ERROR    Vertical metrics. Changes that must be applied to this font: hhea ascent from 1536 to 2088 | OS/2 sTypoAscender from 1536 to 2088 | OS/2 usWinAscent from 1950 to 2088 | hhea descent from -512 to -558 | OS/2 sTypoDescender from -512 to -558 | OS/2 usWinDescent from 550 to 558 | hhea lineGap from 452 to 0 | OS/2 sTypoLineGap from 452 to 0  
Traceback (most recent call last):
  File "fontbakery-check-ttf.py", line 3519, in <module>
    main()
  File "fontbakery-check-ttf.py", line 1979, in main
    version_without_comment, comments = name_version.split(";")
ValueError: too many values to unpack
```

It should probably be corrected with a try: and except: argument

**Comment by felipesanches** [comment]
thanks! I'll take a look at your code!
