### ISSUE TITLE
Travis broken due to lxml/etree: "undefined symbol: clock_gettime"

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#962]
```
0.10s$ python fontbakery-check-ttf.py data/test/cousine/*.ttf

Traceback (most recent call last):

  File "fontbakery-check-ttf.py", line 27, in <module>

    import defusedxml.lxml

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/defusedxml/lxml.py", line 13, in <module>

    from lxml import etree as _etree

ImportError: /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/lxml/etree.so: undefined symbol: clock_gettime
```

**Comment by felipesanches** [comment]
This page seems to provide some clues on this issue:
https://community.webfaction.com/questions/17591/lxml-installation-problem

**Comment by anthrotype** [comment]
What version of lxml are you using?
They uploaded just today new universal `manylinux1` wheels to PyPI:
https://pypi.python.org/pypi/lxml/3.6.2

**Comment by felipesanches** [comment]
It seems that the issue was fixed by TravisCI employees :-)

The build is green now.
